### ISSUE TITLE
error

### ISSUE THREAD

**Issue by PTGHJJD** [GerryDazoo/Slinger#1]
Gerry, hi.   Hey thanks for doing this. Excited to keep using my slingbox.  getting this error? 
thanks for any ideas.

![image](https://user-images.githubusercontent.com/80021576/167439798-406fe23a-0385-459c-be3c-2157feea120a.png)

**Comment by GerryDazoo** [comment]
CHeck you slingbox admin password in the config.ini file

**Comment by PTGHJJD** [comment]
Thanks Gerry will do this AM.  I appreciate your help. Thank you.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by GerryDazoo** [comment]
I just uploaded a new version that handles this error gracefully.

 

*	Gerry

**Comment by GerryDazoo** [comment]
OK, here's the deal. I had put in a huge hack to work around the fact that I couldn't figure out how to unwind the piece of perl code that figured out the proper encryption key to use after you got logged into the box. Apparently this code ONLY works with my box. So it might be awhile before I can get this sorted out with a general purpose solution. 
Can you run some perl on your PC? I might be able to send you a small perl script to regenerate the "keys.dat" file for your box.

**Comment by PTGHJJD** [comment]
Thanks Gerry.. that sounds really frustrating.  At this point, it is working for me on the same wifi which is fine for my use case.

If I can help you figure things out for sure I can run some perl to help you test.

Thanks for all your efforts on this.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by GerryDazoo** [comment]
I've got some new code that will get you past this issue. Download the laterst version AND delete the keys.dat file. Hopewfully this will get you on the air.

**Comment by GerryDazoo** [comment]
Closing. Latest version should be OK.

**Comment by PTGHJJD** [comment]
Ok cool thanks for letting me know.. will try it today.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
