### ISSUE TITLE
allow keys from Oz

### ISSUE THREAD

**Issue by flipper2222222** [GerryDazoo/Slinger#10]
hi Gerry,

I have been closely following the issues raised and saw today that you block outside N.America. can you please allow the server with the keys to be accessed from your friends down under in Australia?

thanks in advance.

**Comment by GerryDazoo** [comment]
Give it a go now. If you still have an issue send my the ip address you are trying to connect from.

 

*	Gerry
*	 

From: flipper2222222 ***@***.***> 
Sent: Thursday, July 21, 2022 7:51 AM
To: GerryDazoo/Slinger ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [GerryDazoo/Slinger] allow keys from Oz (Issue #10)

 

hi Gerry,

I have been closely following the issues raised and saw today that you block outside N.America. can you please allow the server with the keys to be accessed from your friends down under in Australia?

thanks in advance.

**Comment by flipper2222222** [comment]
thanks Gerry, I am on holidays away from my slingbox, will do on my return and give you an update.

**Comment by GerryDazoo** [comment]
V3.02 does not require web server access anymore.
