### ISSUE TITLE
lost power cannot reach PR sling

### ISSUE THREAD

**Issue by sp222222** [GerryDazoo/Slinger#103]
Lost power at my server end during this hurricane.
Got back online and my other 3 in house slingers are fine.
I was able to remote into PR and see correct port forwarding as i thought maybe I didn't save the ini on my end correctly before the power went out. Anyways I'm getting this  error:

Error connecting to  ('192.168.1.22', 5956)
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\threading.py", line 932, in _bootstrap_inn
er
    self.run()
  File "C:\Program Files\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "S:\S2022\SLING VLC\SLING VLC\tommysling\ss.py", line 527, in streamer
    boxes = find_slingbox_info()
  File "S:\S2022\SLING VLC\SLING VLC\tommysling\ss.py", line 78, in find_slingbo
x_info
    import netifaces
ModuleNotFoundError: No module named 'netifaces'

Has to be something easy Gerry :) - Can you assist please?

**Comment by sp222222** [comment]
I ran this from ssh and was able to get it back - so somehow the script on the PR side disappeared??
ssh -i privkey -p PORT#  -R 0.0.0.0:SLINGPORT:192.168.1.42:XXXX admini@myhouserouterdotcom (masked out by me)
if I had not put that cmd in my notes of ini file i'd be down :) anyways when you can please assist Sunday or later in the week.

**Comment by GerryDazoo** [comment]
Mike, this really isn't an issue with the server code. Let's follow up in private email. I don't think the script should have disappeared. The original error you reported is because you're missing a python module that's needed to probe your local network for slingboxes when it fails to contact the configured slings ip. 
Error connecting to ('192.168.1.22', 5956)
