### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by D1scoF1sh** [GerryDazoo/Slinger#112]
Hello,

I believe that this software should have a license. Seeing as it's meant to breathe new life into soon to be officially unsupported hardware, and the goal is to help as many people as possible do such a thing, I think it should be licensed under something like GPL 3.0.

**Comment by sp222222** [comment]
- Getting a copyright disclaimer???   - 
ask charlie  to sign a copyright disclaimer for the program, so it cannot later claim that the copyright belongs to it and that you had no right to release the program at all.  - sounds like trouble - don't want charlie on our backs.  --- but it's not for me to say either way; only how GPL works..

**Comment by GerryDazoo** [comment]
Not gonna do it.
