### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by Mover480** [GerryDazoo/Slinger#12]
Gerry,
Thanks for putting this all together.

I have a couple questions.

1. Say I buy a slingbox off of ebay after sling shuts down their servers later this year.  Will there be any way to set that box up using what you have put together?  Will there be any way to get the password?
2. Right now, if someone has the ip and port number to my slingbox server, they're into what ever is connected to my slingbox.  Is there any way to require a password for this access?
3. In the Remote section of config.sys the button color is set. Is there a way to set the color for individual buttons?

Thanks,
JR

**Comment by GerryDazoo** [comment]
From: Mover480 ***@***.***> 
Sent: Monday, July 25, 2022 6:32 PM
To: GerryDazoo/Slinger ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [GerryDazoo/Slinger] Some questions (Issue #12)

 

Gerry,
Thanks for putting this all together.

I have a couple questions.

1.	Say I buy a slingbox off of ebay after sling shuts down their servers later this year. Will there be any way to set that box up using what you have put together? Will there be any way to get the password?

Based on what I know now. There is no way to recover the passwords for the 500’s. There may be a way to reset the password on the Solo but that’s not on my radar at this point. My hope is the back office servers that have to user account information may stay alive but only time will tell. 

2.	Right now, if someone has the ip and port number to my slingbox server, they're into what ever is connected to my slingbox. Is there any way to require a password for this access? 

Besides the IP and port they would also need to know to use /slingbox in the request. Let me think about allowing the user to configure the URL. Security through obfuscation. You could use your firewall to only allow access from IP addresses you trust.

3.	In the Remote section of config.sys the button color is set. Is there a way to set the color for individual buttons?

Yes. I think that should be possible with multiple style definitions but I don’t have time to look into now. I’ve got Solo remote control issues I need to sort out first.

Thanks,
JR

**Comment by GerryDazoo** [comment]
OK. The latest version 2.05 allows you to specify individual styles per button.
So for example in the styles section of the [REMOTE] section in config.ini you could have something like below which defines the default button style and a red-button style.
style=.button {
      border: none;
      color: white;
      background-color: blue;
      padding: 0px 20px;
      text-align: center;
      text-decoration: none;
      display: inline-block;
      font-size: 70px;
      margin: 4px 2px;
     cursor: pointer;
    }
    
    .red-button {
      border: none;
      color: white;
      background-color: red;
      padding: 0px 20px;
      text-align: center;
      text-decoration: none;
      display: inline-block;
      font-size: 70px;
      margin: 4px 2px;
     cursor: pointer;
    }
    
    .text {
      border: none;
      color: black;
      background-color: lightblue;
      text-align: center;
      text-decoration: none;
      display: inline-block;
      font-size: 70px;
      margin: 4px 2px;
      cursor: pointer;
    }

Then you can at the button class to the button definition i.e.

buttons='1' : 9 
        :&nbsp;&nbsp;
        '2' : 10 : red-button
         :&nbsp;&nbsp;
        '3' : 11 
.....

This would make the "2" button red.

**Comment by Mover480** [comment]
Thanks Gerry

I updated the Tivo Bolt Remote file but am unable to upload it into the Custom Remote section.  

It says:
Uploads are disabled.
File uploads require push access to this repository.

So I'll just attach it here for you to upload.  You can delete the other one if you wish.

[New Tivo Bolt Remote.txt](https://github.com/GerryDazoo/Slinger/files/9193136/New.Tivo.Bolt.Remote.txt)

JR

**Comment by GerryDazoo** [comment]
What kind of boxes are you using? I've got a guy with a Solo box who says no buttons work on his remote. All thought it's working fine for the Solo at my house.

**Comment by Mover480** [comment]
I have two Slingbox 500's.  So I can't help out with the Solo remote  

One Slingbox is connected to a Tivo Bolt and the other one is connected to a Tivo Premiere.  Since the 500's can have three different inputs (composite, component, HDMI), will your code be able to select the input or will it use whatever the box is currently set to.  In the future, without the desktop slingplayer, we may not be able to have an input control option.

The slingbox connected to the Bolt has a video resolution in VLC of 1280x720. It uses an HDMI cable for input from the Tivo.
The slingbox connected to the Premiere has a video resolution in VLC of 1280x540.  It uses component cables from the Tivo.  I don't understand where the 540 is coming from.  Both Tivo's are set to a video resolution of 1080i and display just fine on HD TV's.  Any ideas?

JR

**Comment by GerryDazoo** [comment]
I’ve seen this. I’ve got some notes somewhere. The slingbox does not “down convert” to just throws away every second scan line. So 1920x1080 turns into a resolution  blah:540.

 

*	Gerry

**Comment by Mover480** [comment]
Gerry,
Here is another Remote file.
[Tivo Premiere Remote.txt](https://github.com/GerryDazoo/Slinger/files/9213083/Tivo.Premiere.Remote.txt)

**Comment by GerryDazoo** [comment]
While you doing fancy stuff with the remote, here’s how to make a round button, Note the double %%. Needed to get the python code to properly parse the special character.

 

Round Button

style=.round {

      border: none;

      color: white;

      background-color: blue;

      padding: 0px 20px;

      text-align: center;

      text-decoration: none;

      display: inline-block;

      font-size: 70px;

      margin: 4px 2px;

     cursor: pointer;

     border-radius: 50%%;

    }

**Comment by GerryDazoo** [comment]
On second thought I’ll change the code to make this adjustment. Should be in the next version. But you can still the  %% until then.

 

From: Gerry Dubois ***@***.***> 
Sent: Friday, July 29, 2022 10:06 AM
To: 'GerryDazoo/Slinger' ***@***.***>; 'GerryDazoo/Slinger' ***@***.***>
Cc: 'Comment' ***@***.***>
Subject: RE: [GerryDazoo/Slinger] Some questions (Issue #12)

 

While you doing fancy stuff with the remote, here’s how to make a round button, Note the double %%. Needed to get the python code to properly parse the special character.

 

Round Button

style=.round {

      border: none;

      color: white;

      background-color: blue;

      padding: 0px 20px;

      text-align: center;

      text-decoration: none;

      display: inline-block;

      font-size: 70px;

      margin: 4px 2px;

     cursor: pointer;

     border-radius: 50%%;

    }

**Comment by Mover480** [comment]
Gerry,
I get an error using the round button.
Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by GerryDazoo** [comment]
I’ll need your config.ini to test with.

**Comment by Mover480** [comment]
Here ya go
[config.txt](https://github.com/GerryDazoo/Slinger/files/9221573/config.txt)

**Comment by GerryDazoo** [comment]
Two things

1.	On line 124 you inadvertently deleted the ; in front of the comment button text, key code
2.	When I said this was working I was a little wrong. I had been testing a new feature where you can include a remote definitions file instead of having it embedded in the config.ini file. Long story short, the python config file parsing routines were behaving differently from my code. So, this may sound weird please replace %% with %%%% in your file. And you should  be good to go. I’ll try to clean this up in the next version.

 

*	gerry

**Comment by Mover480** [comment]
Works fine, thanks

**Comment by GerryDazoo** [comment]
If your good to go, I'd like to close this issue.

**Comment by Mover480** [comment]
OK

**Comment by GerryDazoo** [comment]
Thanks for all your help finding my bugs.
