### ISSUE TITLE
Pro-HD and remote question

### ISSUE THREAD

**Issue by jmcexx** [GerryDazoo/Slinger#13]
First, want to let you know the server worked straight away with the Slingbox Pro-HD I have.  Fantastic job!  Streaming video/audio working great.  Thank you for all this.

The remote does not work for me yet.  I can access the page with buttons and the server sees me pressing them.  It sounds like you have not tested with Pro-HD or the specific remote I need to emulate (Xfinity DTA).  So, this may not be configured right.  I'd like to help figure that out.      

Below is what it prints on button press.  I see no response from the TV tuner like I pressed the actual remote, but does it look correct?  I thought my next step might be to see if the Pro-HD is actually sending any IR signal when I press the button.  

```
Jul 26 08:05:13 ITAM-4 python3[2123]: Remote Control Connected
Jul 26 08:05:13 ITAM-4 python3[2123]: Button Clicked ImmutableMultiDict([('2', '10'), ('Digits', '')])
Jul 26 08:05:13 ITAM-4 python3[2123]: 127.0.0.1 - - [26/Jul/2022 08:05:13] "POST /Remote HTTP/1.1" 200 -
Jul 26 08:05:14 ITAM-4 python3[2123]: Got Streamer Control Message IR b'\n\x00\x00\x00\x00\x00\x00\x00'
Jul 26 08:05:14 ITAM-4 python3[2123]: No request in time, hacker?
Jul 26 08:05:17 ITAM-4 python3[2123]: .07/26/2022, 08:05:17   connection from ('12.68.171.101', 36899)
Jul 26 08:05:17 ITAM-4 python3[2123]: [1B blob data]
```

**Comment by GerryDazoo** [comment]
Standby, some other people have issues with the solo/pro remote. I’ll have a new version available soon.

 

*	Gery

 

From: jmcexx ***@***.***> 
Sent: Tuesday, July 26, 2022 10:30 AM
To: GerryDazoo/Slinger ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [GerryDazoo/Slinger] Pro-HD and remote question (Issue #13)

 

First, want to let you know the server worked straight away with the Slingbox Pro-HD I have. Fantastic job! Streaming video/audio working great. Thank you for all this.

The remote does not work for me yet. I can access the page with buttons and the server sees me pressing them. It sounds like you have not tested with Pro-HD or the specific remote I need to emulate (Xfinity DTA). So, this may not be configured right. I'd like to help figure that out.

Below is what it prints on button press. I see no response from the TV tuner like I pressed the actual remote, but does it look correct? I thought my next step might be to see if the Pro-HD is actually sending any IR signal when I press the button.

Jul 26 08:05:13 ITAM-4 python3[2123]: Remote Control Connected
Jul 26 08:05:13 ITAM-4 python3[2123]: Button Clicked ImmutableMultiDict([('2', '10'), ('Digits', '')])
Jul 26 08:05:13 ITAM-4 python3[2123]: 127.0.0.1 - - [26/Jul/2022 08:05:13] "POST /Remote HTTP/1.1" 200 -
Jul 26 08:05:14 ITAM-4 python3[2123]: Got Streamer Control Message IR b'\n\x00\x00\x00\x00\x00\x00\x00'
Jul 26 08:05:14 ITAM-4 python3[2123]: No request in time, hacker?
Jul 26 08:05:17 ITAM-4 python3[2123]: .07/26/2022, 08:05:17   connection from ('12.68.171.101', 36899)
Jul 26 08:05:17 ITAM-4 python3[2123]: [1B blob data]

**Comment by GerryDazoo** [comment]
please try the latest version 2.04.

**Comment by GerryDazoo** [comment]
Also, please confirm it's working with the SlingPlayer/SlingPlayerforWeb sofware

**Comment by jmcexx** [comment]
I confirmed that the remote is working through SlingPlayerforWeb.  The digits control the tuner.

I'm running your v2.05 now.  But the result is the same.  No response from the tuner.

**Comment by GerryDazoo** [comment]
Thx for the update.

**Comment by GerryDazoo** [comment]
Are you using the python version? I’d like to send you a private test version for you to try.

 

*	Gerry

**Comment by jmcexx** [comment]
Yes, I'm using python version.  Glad to try it.

**Comment by GerryDazoo** [comment]
Here you go. Fingers crossed.

 

*	Gerry

**Comment by GerryDazoo** [comment]
[slingbox_server_test.txt](https://github.com/GerryDazoo/Slinger/files/9198803/slingbox_server_test.txt)

GITHUB blocked the .py file extension
rename to .py

**Comment by jmcexx** [comment]
Thank you.  I run the test version and get the same result.  Here is the log when I press 1, 2, 3 on remote webpage:
```
Jul 27 11:30:20 ITAM-473 python3[27247]: 07/27/2022, 11:30:20   connection from ('192.168.1.23', 18097)
Jul 27 11:30:20 ITAM-473 python3[27247]: [1B blob data]
Jul 27 11:30:20 ITAM-473 python3[27247]: Starting remote control stream hander for  ('192.168.1.23', 18097)
Jul 27 11:30:20 ITAM-473 python3[27247]: 07/27/2022, 11:30:20   connection from ('192.168.1.23', 18098)
Jul 27 11:30:20 ITAM-473 python3[27247]: Remote Control Connected
Jul 27 11:30:20 ITAM-473 python3[27247]: Button Clicked ImmutableMultiDict([('1', '9'), ('Digits', '')])
Jul 27 11:30:20 ITAM-473 python3[27247]: 127.0.0.1 - - [27/Jul/2022 11:30:20] "POST /Remote HTTP/1.1" 200 -
Jul 27 11:30:20 ITAM-473 python3[27247]: Got Streamer Control Message IR b'\t\x00\x00\x00\x00\x00\x00\x00'
Jul 27 11:30:20 ITAM-473 python3[27247]: sling_cmd
Jul 27 11:30:20 ITAM-473 python3[27247]: Sent to Slingbox  0x87 0xf0 0x1e0
Jul 27 11:30:20 ITAM-473 python3[27247]: Received from Slingbox 2792 0x0 0
Jul 27 11:30:20 ITAM-473 python3[27247]: No request in time, hacker?

Jul 27 11:30:24 ITAM-473 python3[27247]: 07/27/2022, 11:30:24   connection from ('192.168.1.23', 18099)
Jul 27 11:30:24 ITAM-473 python3[27247]: [1B blob data]
Jul 27 11:30:24 ITAM-473 python3[27247]: Starting remote control stream hander for  ('192.168.1.23', 18099)
Jul 27 11:30:24 ITAM-473 python3[27247]: 07/27/2022, 11:30:24   connection from ('192.168.1.23', 18100)
Jul 27 11:30:24 ITAM-473 python3[27247]: Remote Control Connected
Jul 27 11:30:24 ITAM-473 python3[27247]: Button Clicked ImmutableMultiDict([('2', '10'), ('Digits', '')])
Jul 27 11:30:24 ITAM-473 python3[27247]: 127.0.0.1 - - [27/Jul/2022 11:30:24] "POST /Remote HTTP/1.1" 200 -
Jul 27 11:30:24 ITAM-473 python3[27247]: Got Streamer Control Message IR b'\n\x00\x00\x00\x00\x00\x00\x00'
Jul 27 11:30:24 ITAM-473 python3[27247]: sling_cmd
Jul 27 11:30:24 ITAM-473 python3[27247]: Sent to Slingbox  0x87 0xf3 0x1e0
Jul 27 11:30:24 ITAM-473 python3[27247]: Received from Slingbox 2792 0x0 0
Jul 27 11:30:24 ITAM-473 python3[27247]: No request in time, hacker?

Jul 27 11:30:25 ITAM-473 python3[27247]: .sling_cmd
Jul 27 11:30:27 ITAM-473 python3[27247]: 07/27/2022, 11:30:27   connection from ('192.168.1.23', 18101)
Jul 27 11:30:27 ITAM-473 python3[27247]: No request in time, hacker?
Jul 27 11:30:27 ITAM-473 python3[27247]: 07/27/2022, 11:30:27   connection from ('192.168.1.23', 18102)
Jul 27 11:30:27 ITAM-473 python3[27247]: [1B blob data]
Jul 27 11:30:27 ITAM-473 python3[27247]: Starting remote control stream hander for  ('192.168.1.23', 18102)
Jul 27 11:30:27 ITAM-473 python3[27247]: Remote Control Connected
Jul 27 11:30:27 ITAM-473 python3[27247]: Button Clicked ImmutableMultiDict([('3', '11'), ('Digits', '')])
Jul 27 11:30:27 ITAM-473 python3[27247]: 127.0.0.1 - - [27/Jul/2022 11:30:27] "POST /Remote HTTP/1.1" 200 -
Jul 27 11:30:27 ITAM-473 python3[27247]: Got Streamer Control Message IR b'\x0b\x00\x00\x00\x00\x00\x00\x00'
Jul 27 11:30:27 ITAM-473 python3[27247]: sling_cmd
Jul 27 11:30:27 ITAM-473 python3[27247]: Sent to Slingbox  0x87 0xf2 0x1e0
Jul 27 11:30:27 ITAM-473 python3[27247]: Received from Slingbox 2792 0x0 0
```

I did confirm using wireshark that both slinger and the webPlayer sends 512byte commands to the slingbox when remote keys are pressed.  I don't understand enough to see what may be different yet, though.

**Comment by GerryDazoo** [comment]
Thanks for the update. On the wireshark traces can you confirm the first two bytes of the payload are 01 01 from both my code and Sling. You won’t be able to tell much from the captures because all the important stuff is encrypted. I do have some code (perl/python) that we can use sort of a Man In The Middle proxy to snoop and decrypt the data streams in real time but it’s a bear to set up. Be then we could see exactly what Sling is sending to your box and we could then emulate that in my code.

 

*	Gerry

 

P.S. I’m a little concerned by all the “No response in time” logs. When I was getting port scanned unmercifully I had the server shutdown the connection if it didn’t get a valid GET/POST packet within 200 mSec of the connection being opened. So that shouldn’t be happening in normal operation

**Comment by jmcexx** [comment]
Very cool!  Yes, it does start with 01 01.

Here's start of IR command from SlingPlayer (total is 512 bytes):
```
0030                     01 01 7d 1d 87 00 00 00 bf 00
0040   00 00 00 00 00 00 e0 01 00 80 00 00 00 00 e2 00
0050   00 00 00 00 00 00 cd 6b 6f 7b dd 3a 0c 00 28 cb
0060   29 0e 18 42 58 76 28 cb 29 0e 18 42 58 76 28 cb
```

For comparison, here's what your slinger sends:
```
0030                     01 01 80 72 87 00 00 00 6d 00
0040   00 00 00 00 00 00 e0 01 00 80 00 00 00 00 eb 00
0050   00 00 00 00 00 00 19 4b 71 84 07 1a 06 ae f3 47
0060   e6 d2 bf eb 4e 22 f3 47 e6 d2 bf eb 4e 22 f3 47
```

I'm glad to try capture. <username>@gmail?

**Comment by GerryDazoo** [comment]
Can you send me the pcap of all the packets to and from the slingbox when using Slingplayer. It might be easier for me to whip up some code to replay the packets and pass it thru my proxy. You can email me directly ***@***.*** ***@***.***> 

 

*	Gerry

**Comment by GerryDazoo** [comment]
Can you save it as a pcap.

**Comment by jmcexx** [comment]
Just that message?  Or do you want a full log that would include the connection/authentication?

**Comment by GerryDazoo** [comment]
The full log so I can snoop the data to generate the encryption keys to allow decoding the IR message.

**Comment by jmcexx** [comment]
That's great.  Here's a pcap of only the "control" TCP connection.  If that doesn't have what you need, I can send the full capture, but it's large (20MB).

In this I connect to slingbox PRO-HD with slingplayer for web.  As soon as video comes up I bring up remote and press 1 then 2 then 3.  Then just shutoff log.  Please advise if something else would be better.


[webplayer_remote_123_control_only.zip](https://github.com/GerryDazoo/Slinger/files/9203904/webplayer_remote_123_control_only.zip)

**Comment by GerryDazoo** [comment]
That should be sufficient. Thx.

 

*	Gerry

**Comment by jmcexx** [comment]
Great, I will try it out.  Unfortunately I won't be able to try until tomorrow morning.  But I have high hopes.  Thanks

**Comment by GerryDazoo** [comment]
Can you also share you’re box’s firmware and hardware version. I’m trying to figure out if there is some correlation with the remote configuration.

**Comment by jmcexx** [comment]
Amazing ... that works!  I'm able to do the basic remote control now.

```
Slingbox Pro-HD
Slingbox Model #:   SB300-XXX   
P/N:                980-10016
Firmware Version:   2.1.420
Hardware Version:   1.1.0
```

Model and part number are from sticker on the device.  Firmware and hardware version are reported from slingbox player.  So, I'm guessing it is actually model #SB300-110.

Again, I have to thank you for working on this.  It's very exciting and impressive.  I hope to be able to help a bit moving forward.

**Comment by GerryDazoo** [comment]
I have one more request.

Can you change the source code and try some different values. On line 570 “end=0”

Can you try end=1 end=2 and end=3 and report the results.

I thinking this number may refer to the remote to use for the different video sources. I’ve got my fingers crossed that 0 = the current source selection. I’ve seen all three values in my testing.

 

*	Gerry

**Comment by GerryDazoo** [comment]
Can I assume that when you say basic control, that some buttons aren’t working? On some remotes not all functions are mapped to the same key id. IN the default config.ini I listed the valid keys mapped for my remote. Yours may be different.

To get your specific keycodes you can connect to your box with Desktop. I’ll send more detailed info shortly. Then once you have the key codes delta you can test the codes.

To send a test code to the slingbox prefix the code with a ? and put it in the “Channel” field. i.e. ?35 will send the Guide command.

 

Then you can update the remote configuration section in your config.ini file.

 

*	Gerry

**Comment by GerryDazoo** [comment]
To get your codes run slingplayer, Then

singbox directory/your box/edit/information/IR key codes/key codes

 

** You may have to set the clock back in your PC to get it to run…..

 

*	Gerry

 

From: Gerry Dubois ***@***.***> 
Sent: Friday, July 29, 2022 9:43 AM
To: 'GerryDazoo/Slinger' ***@***.***>; 'GerryDazoo/Slinger' ***@***.***>
Cc: 'Comment' ***@***.***>
Subject: RE: [GerryDazoo/Slinger] Pro-HD and remote question (Issue #13)

 

Can I assume that when you say basic control, that some buttons aren’t working? On some remotes not all functions are mapped to the same key id. IN the default config.ini I listed the valid keys mapped for my remote. Yours may be different.

To get your specific keycodes you can connect to your box with Desktop. I’ll send more detailed info shortly. Then once you have the key codes delta you can test the codes.

To send a test code to the slingbox prefix the code with a ? and put it in the “Channel” field. i.e. ?35 will send the Guide command.

 

Then you can update the remote configuration section in your config.ini file.

 

*	Gerry

**Comment by jmcexx** [comment]
end=0  Works
end=1  NO
end=2  NO
end=3  NO
end=0  Works ... just checking

In my case, the slingbox is using the COAX RF input (always tuned to ch3).  To your idea maybe that is input 0.

I only have a simple tuner, so the remote only has a few buttons.  I think all the buttons which you have on your web page which are on the remote, do work.  There are one or two which are not on your default page.  I'll look into the remote stuff you sent.

**Comment by jmcexx** [comment]
Thanks for your instructions.  I updated the .ini to to match my remote.  It's not pretty, but all the buttons work right.  
[Xfinity.Dta.Remote.txt](https://github.com/GerryDazoo/Slinger/files/9221798/Xfinity.Dta.Remote.txt)

**Comment by jmcexx** [comment]
It's probably worth you mentioning that depending on how much buffering the player has, the remote may seem really delayed.  It's easy to get frustrated.  

At one point I had 25 seconds delay, but typically it closer to 4 seconds.  This was just using default VLC settings.  I think there are ways to configure it to reduce this delay.  Good enough for now.

**Comment by GerryDazoo** [comment]
I think that’s in the readme. Yes, you can spend some time trying to minimize VLC delays. After awhile I gave up and switch to ffplayer with this command line. With that the remote is mostly usable (still a bear for stopping FF/REW at the right place.

 

C:\ffmpeg\ffplay.exe -infbuf -probesize 32 -analyzeduration 0 -vf scale=1280x720 -flags nobuffer -flags low_delay http://127.0.0.1:8082/slingbox

**Comment by GerryDazoo** [comment]
Just another comment, I to have seen very long delays as you noticed. 

Depending on your hardware the video rendering starts to fall behind and the delays start to build up. Even though task manager shows everything is ticitly-boo as far as GPU resources go. 

What I did was reduce the video bandwidth and VLC started to keep up. Then I finally moved to ffplayer.

 

*	Gerry

**Comment by GerryDazoo** [comment]
[slingbox_server.txt](https://github.com/GerryDazoo/Slinger/files/9225810/slingbox_server.txt)

I'd appreciate you taking this for a test drive. So you won't need a custom version of the source code to get your remote to work.

Here’s a quick summary. I’ve added a mechanism to probe for the proper remote control base configuration. There's a new button (add the following text to the end of your config.ini)

       'RT'  :  RCtest

When you press this button it will send out a “power” IR command. If you see the power go off, then make a note of the status line at the bottom of your webpage, test the other buttons power on of course….
If al looks good then we can update your config.ini with the discovered information. If the power doesn’t go off then hit the RT button again and it will test the next code. Repeat until you find a working code.
Updating the config.ini
In the [REMOTE] section add this line
code=xxxx
Where xxx is the code you noted above
Please let me know how it works out and what code you were successful in using.
I'm more convinced than ever that this magic number corresponds with the configured video sources.

- Gerry

P.S. If your device doesn't have a power button option, try some of the other basic keys.

**Comment by jmcexx** [comment]
I will give that a try a bit later today.  

The sling player seems to allow you to assign separate remotes for each of the video input sources.  So it makes sense the command needs to select which one to use.

**Comment by jmcexx** [comment]
0, 250, 500, and 1000 work, all others do not.
FWIW, it gets stuck when RT exceeds 1003.

**Comment by GerryDazoo** [comment]
Yes, I’ve managed to figure out how to sect the different video input. But selecting different remote definitions on the fly complicates things. Right now to get thing going I’m thinking about being able to select the input in the config.ini file and then being able to pass a config file name in on the command line. The different config files would define different sources and remote config files.

 

*	Gerry

**Comment by GerryDazoo** [comment]
That’s what I was hoping for. It’s the video source, in your case 0, The other data that was in the wireshark trace doesn’t seem to be used. 

The RT command was supposed to wrap around. I’ll fix that.

 

*	Gerry

**Comment by GerryDazoo** [comment]
If you wouldn’t mind, When using Slingplayer there’s a settings button that allows you to select a video source. Can you tell me what those are in order on your box?

 

*	Gerry

 

From: Gerry Dubois ***@***.***> 
Sent: Saturday, July 30, 2022 1:55 PM
To: 'GerryDazoo/Slinger' ***@***.***>; 'GerryDazoo/Slinger' ***@***.***>
Cc: 'Comment' ***@***.***>
Subject: RE: [GerryDazoo/Slinger] Pro-HD and remote question (Issue #13)

 

Yes, I’ve managed to figure out how to sect the different video input. But selecting different remote definitions on the fly complicates things. Right now to get thing going I’m thinking about being able to select the input in the config.ini file and then being able to pass a config file name in on the command line. The different config files would define different sources and remote config files.

 

*	Gerry

**Comment by jmcexx** [comment]
The input I'm using is the first one (coax).  Order: Coax, Composite, S-Video, Component.

![image](https://user-images.githubusercontent.com/17991666/181936308-5ed661ef-ff91-4406-8dcd-e735ee66e32a.png)

So, that's cool what you found,  My issue wasn't that the IR command is somehow different for PRO-HD, but that it was commanding the wrong remote.  I like your suggestion of different config files ... keeps it simple.

**Comment by GerryDazoo** [comment]
Grab the latest version 3.00. Supports different config files to sort out your remotes problem, Check details in the release notes

**Comment by GerryDazoo** [comment]
I have one more ask. I think I've figured out how to extract the remote keycodes from the slingbox. Can you run this test version and report back what you get. It will look something like this.
Keycodes 000000 01 12 09 0a 0b 0c 0d 0e 0f 10 11 04 05 01 21 22
000016 2e 2a 15 16 26 27 28 29 2d 17 23 2b 2c 18 1a 1b
000032 1c 19 1d 25 2f 13 1f 20 35 36 37 38 39 3a 3b 3c
000048 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
000064 00 00 00 00 00
[slingbox_server_test.txt](https://github.com/GerryDazoo/Slinger/files/9242403/slingbox_server_test.txt)
 00 00 00 00 00 00 00 00 00 00 00
000080 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
000096 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
000112 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
000128 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
000144 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
000160 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
000176 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
000192 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
000208 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
000224 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
000240 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00

**Comment by jmcexx** [comment]
I will check it out soon.  Thanks.

**Comment by GerryDazoo** [comment]
I think I managed to sort this out. Thanks for all your help.
I'm going to close this issue.
