### ISSUE TITLE
Seeing this utf-8 error

### ISSUE THREAD

**Issue by jacoats** [GerryDazoo/Slinger#145]
![slinger error](https://user-images.githubusercontent.com/38011127/196478295-672cf05d-1d02-480d-a67d-e6776c39dd4f.jpg)
Seeing this UTF-* unicode error.  I think it was triggered by a remote user.  Ended up hanging the server and had to reboot my W10 PC.    Using config.ini V3.08

**Comment by GerryDazoo** [comment]
You shouldn't have had to reboot your PC. But it does look like you got port scanned. Next time please post the text not a screenshot. But this does look like a bug. The server should not stop responding whatever you throw at it. I'll take a look.

**Comment by GerryDazoo** [comment]
I'll have an update out shortly. Tomorrow.....
