### ISSUE TITLE
Streaming cuts out while watching

### ISSUE THREAD

**Issue by shadowscott** [GerryDazoo/Slinger#15]
Connecting... ('192.168.1.121', 5201) Control
Keycodes= []
VideoParameters: Resolution= 15 FrameRate= 60 VideoBandwidth= 3000 VideoSmoothness= 63 IframeRate= 5 AudioBitRate= 48
Connecting... ('192.168.1.121', 5201) Stream
Stream started at 08/06/2022, 18:49:25  749 0
........08/06/2022, 18:50:55   1 Clients.(IP edited out)
08/06/2022, 18:50:56   Stream Terminated for  (IP edited out) [Errno 11] Resource temporarily unavailable
Shutting down connections
Streamer:   Waiting for first stream, flushing any IR requests that arrive while not connected to slingbox

**Comment by GerryDazoo** [comment]
Are you running on Linux?

 

From: shadowscott ***@***.***> 
Sent: Saturday, August 06, 2022 7:55 PM
To: GerryDazoo/Slinger ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [GerryDazoo/Slinger] Streaming cuts out while watching (Issue #15)

 

Connecting... ('192.168.1.121', 5201) Control
Keycodes= []
VideoParameters: Resolution= 15 FrameRate= 60 VideoBandwidth= 3000 VideoSmoothness= 63 IframeRate= 5 AudioBitRate= 48
Connecting... ('192.168.1.121', 5201) Stream
�Stream started at 08/06/2022, 18:49:25 749 0
........08/06/2022, 18:50:55 1 Clients.(IP edited out)
08/06/2022, 18:50:56 Stream Terminated for (IP edited out) [Errno 11] Resource temporarily unavailable
�Shutting down connections
Streamer: Waiting for first stream, flushing any IR requests that arrive while not connected to slingbox

**Comment by GerryDazoo** [comment]
Are you running on Linux?

 

 

From: shadowscott ***@***.***> 
Sent: Saturday, August 06, 2022 7:55 PM
To: GerryDazoo/Slinger ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [GerryDazoo/Slinger] Streaming cuts out while watching (Issue #15)

 

Connecting... ('192.168.1.121', 5201) Control
Keycodes= []
VideoParameters: Resolution= 15 FrameRate= 60 VideoBandwidth= 3000 VideoSmoothness= 63 IframeRate= 5 AudioBitRate= 48
Connecting... ('192.168.1.121', 5201) Stream
�Stream started at 08/06/2022, 18:49:25 749 0
........08/06/2022, 18:50:55 1 Clients.(IP edited out)
08/06/2022, 18:50:56 Stream Terminated for (IP edited out) [Errno 11] Resource temporarily unavailable
�Shutting down connections
Streamer: Waiting for first stream, flushing any IR requests that arrive while not connected to slingbox

**Comment by shadowscott** [comment]
Yes. This is running on a raspberry pi zero

**Comment by GerryDazoo** [comment]
The log indicates that you are running out of TCP buffers. This could be due to a number of things.
1) Please verify you've bumped up the number of buffers as described in the readme
2) The software you're using isn't keeping up with the stream. Try chnaging the VIdeoBandwidth to a lower number.
Are you connecting locally or remotely? if remotely then you may be running out of bits on your internet uplink. 
What networking interface are you using on the Pi Zero? Zero M? You may have some bandwidth issues on your wireless connection (assuming it's wireless)

**Comment by GerryDazoo** [comment]
Also run a "top" to verify your not running out of CPU juice. But I doubt it...

**Comment by shadowscott** [comment]
For the buffer are you referring to this?

Add or modify the two following lines to your /etc/sysctl.conf 
    net.core.rmem_max = 8192000
    net.core.wmem_max = 8192000

I'm using a raspberry pi zero would I need to change this to match the RAM on that device instead?

**Comment by GerryDazoo** [comment]
No, that's only 8M. Should be OK

**Comment by shadowscott** [comment]
Okay. Just made the change and rebooted. I did update VideoResolution, frame rate, and Audio Bitrate as I wanted higher quality. Top is showing <20% CPU and I am right next to the router and should have bandwidth. 25Mbps Up. Also, I AM connecting remotely.

**Comment by GerryDazoo** [comment]
If there is a bottleneck it “might” be the wireless. I’m pretty sure only a cheapie 2.4Ghz radio is used. Can you run an “iperf” session to see what you’re really getting.

Also, can you try it not roaming on the local network. That would take a lot of possible issues off the table.

 

*	Gerry

 

P.S. 20 percent CPU is fine. It’d be concerned if it went above 80%

**Comment by shadowscott** [comment]
I used speedtest-cli that I found on github and was getting roughly 6 Mbps up. Unfortunately can not connect locally as it isn't with me. I did add in the 8MB buffer as you said (must've missed that step originally) and bumped the videobitrate up to 8000 and audio up to 96 and its been holding steady with just 1 remote connection.

**Comment by GerryDazoo** [comment]
Well, that’s good news. So are you using the W model? A lot of people are going to like knowing they could get some hardware to run their server code on for $10.00. What is the power rating for the Zero. Wondering if it could be powered off a USB port on the router.

**Comment by shadowscott** [comment]
Pi Zero W gen 1 off the USB port of the slingbox itself actually. I did have to drop my video bitrate to default and audio to 48 at 1080p and 60fps. 

When I had two streams it would start to pause on 96 and 8000. So I'm guessing that's bandwidth on my internet. I'll have to look into USB Ethernet or USB WiFi that runs better than built in.

**Comment by GerryDazoo** [comment]
Sorry, I thought I had responded to this. My number one guess it's issues with the wireless. Try a wired Ethernet interface and see how it works.

**Comment by GerryDazoo** [comment]
Let's move this to discussions, if you need anymore help.
