### ISSUE TITLE
How will you be able to grab the Slingbox admin password when the servers die?

### ISSUE THREAD

**Issue by larsenv** [GerryDazoo/Slinger#186]
Is there any way you can grab the admin password from the Slingbox in the case they shut the endpoint down when they discontinue the Slingbox soon? Or is that something we don't know yet? No matter how much you publicize this, I'm sure there will be people that don't know about this project after the discontinuation date.

Nice work on this by the way. I don't think the Slingbox is a relevant technology in 2022, but it's nice to support those who want to use this technology. I wish I got to experience the Slingbox back when it was more relevant.

**Comment by GerryDazoo** [comment]
There is no way to recover the the password from the slingbox.
However, people have reported that the password is finadable in the slingbox desktop log file.

**Comment by rblancarte** [comment]
So interesting thing I found a few days back, the password changes on factory reset. I factory reset mine the other day, re-set it up and the PW had changed.

**Comment by GerryDazoo** [comment]
Yes, I can confirm that.

**Comment by RandomMan719** [comment]
With the older models, Solo/pro/proHD.  You should be able to set the admin password, during setup with slingplayer 2.0, without connecting to the servers.

**Comment by GerryDazoo** [comment]
I haven't been able to make that work. There is an option to change the password but it doesn't work because the Sling servers need to be informed of the new password to be able to start future video streams.
