### ISSUE TITLE
after upgrade to v3.08 status no more work

### ISSUE THREAD

**Issue by alfuxj** [GerryDazoo/Slinger#209]
before upgrade status in remote web page display how many client connection , now no more only say waiting for first client .
is  my configuration problem or have a bug?

**Comment by GerryDazoo** [comment]
Maybe a bug. Please reply with contents of your remote config file.

**Comment by alfuxj** [comment]
i use the remote inside  slingbox_server.py . version 3.07 work perfect for me . maybe i have misconfiguration.  
this is my config.ini 

[SLINGBOX]
sbtype="350/500/M1/M2"
;sbtype="Solo/Pro/ProHD"
;sbtype="240"
password=xxxxxxxxxxxx
; uncomment the next lines ipaddress and port with your local network info
; if you don't want the server to automatically find your
; slingbox on the local network. Needed if server and slingbox are
; not on the same LAN segment. Also removes requirement for the netifaces module
ipaddress=xxxx.xxxxx.org
port=5201
; Repace with your finderid, If and only if you need remote access and don't
;have a static ip and you plan on using my service to access you server remotely.
; Please read the release notes. Most people don't need this.
;finderid=BAD95DAED609364Cxxxxxxxxxxxxxxxxxxxxxx

;If you've got more than one slingbox set name. THe server will use this when generating
; logs to make it easier to see what's going on.
;name=something

; Following are the default values
; Default resolution when server starts. You can change this and reconnect without having to restart the server
; valid range = 1..15
Resolution=12

; Valid Values 1, 6, 10, 15, 20, 30, 60   depending on resolution
FrameRate=30

;Min 50 Max 8000
VideoBandwidth=4000

; Min 0 (auto) max 63
;VideoSmoothness=63

; Send Iframe every n seconds Max 30
;IframeRate=5

; Audio Bit Rate. Valid Options 16, 20, 32, 40, 48, 64, 96 Default 32
AudioBitRate=32

; Video Source  0, 1, 2, 3 depending on your hardware corrosponds to one of
;Composite, Component, HDMI or Tuner.
;ProHD 0=Tuner, 1=composite 2=svideo 3=component
;Solo, M1 0=composite 1=Svideo 2=component
;500  0=composite, 1=component, 2=HDMI
; If you don't set this the code will use the last configired input
; I recommend setting this value. If not set correctly you'll often only see a black screen.
VideoSource = 2

[SERVER]
; local port number for the server to listen on for connections
port=8082
maxstreams=10
enableremote=yes

[REMOTE]
; see release notes for changing this if your remote doesn't work, But as a start make it
;the same as your configured VideoSource 0-3. See above.
code=1
; path to an external remote control definitions file, if the defaults
; aren't working for you or you want to change the format of the web page.
; use the supplied remote.txt as a starting point.
;include=remote.txt

**Comment by alfuxj** [comment]
i use debian 10 and ubuntu 20 with same result

**Comment by alfuxj** [comment]
you wrote "Please also reply with the server output."   you mean this ?

● sling.service - SlingBox Server Service
   Loaded: loaded (/etc/systemd/system/sling.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2022-11-01 11:11:52 GMT; 36min ago
 Main PID: 5189 (python3)
    Tasks: 4 (limit: 1136)
   Memory: 27.4M
   CGroup: /system.slice/sling.service
           └─5189 /usr/bin/python3 -u slingbox_server.py

**Comment by GerryDazoo** [comment]
It's a bug.  Here's a quick patch for the python code.
Replace "section_name" with "box_name" on line 933.

**Comment by smt171** [comment]
Version 3.08 of what? The remote configuration? Hardware upgrade?

**Comment by smt171** [comment]
Is there a certain firmware we need to be on for Slinger to work? For M1? 500?
