### ISSUE TITLE
I'm a hacker apparently

### ISSUE THREAD

**Issue by cwaddilove** [GerryDazoo/Slinger#21]
All I get are empty responses or failures to connect.

Hacker Alert. Invalid Request from  ('192.168.0.58', 40786)
Hacker Alert. Invalid Request from  ('192.168.0.58', 40787)
Hacker Alert. Invalid Request from  ('192.168.0.58', 40814)
Hacker Alert. Invalid Request from  ('192.168.0.58', 40815)
Hacker Alert. Invalid Request from  ('192.168.0.58', 40816)
192.168.0.58 - - [12/Aug/2022 22:03:23] "GET / HTTP/1.1" 404 -
192.168.0.58 - - [12/Aug/2022 22:03:23] "GET /favicon.ico HTTP/1.1" 404 -
192.168.0.58 - - [12/Aug/2022 22:03:36] "GET / HTTP/1.1" 404 -
192.168.0.58 - - [12/Aug/2022 22:03:36] "GET / HTTP/1.0" 404 -
192.168.0.58 - - [12/Aug/2022 22:05:34] "GET / HTTP/1.1" 404 -
Hacker Alert. Invalid Request from  ('192.168.0.58', 40957)
No request in time, hacker? ('192.168.0.58', 40958)
Hacker Alert. Invalid Request from  ('192.168.0.58', 40960)
Hacker Alert. Invalid Request from  ('192.168.0.58', 40961)
Hacker Alert. Invalid Request from  ('192.168.0.58', 40962)

**Comment by GerryDazoo** [comment]
I suspect you are not supplying the proper URL when connecting.

 

HTTP://serverAddress:port/slingbox

 

HTTP://serverAddress:port/Remote

 

Assuming you haven’t changed the default settings and your running the server on the same pc your trying to connect from

http://192.168.0.58:8080/slingbox

 

 

From: cwaddilove ***@***.***> 
Sent: Friday, August 12, 2022 11:10 PM
To: GerryDazoo/Slinger ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [GerryDazoo/Slinger] I'm a hacker apparently (Issue #21)

 

All I get are empty responses or failures to connect.

Hacker Alert. Invalid Request from ('192.168.0.58', 40786)
Hacker Alert. Invalid Request from ('192.168.0.58', 40787)
Hacker Alert. Invalid Request from ('192.168.0.58', 40814)
Hacker Alert. Invalid Request from ('192.168.0.58', 40815)
Hacker Alert. Invalid Request from ('192.168.0.58', 40816)
192.168.0.58 - - [12/Aug/2022 22:03:23] "GET / HTTP/1.1" 404 -
192.168.0.58 - - [12/Aug/2022 22:03:23] "GET /favicon.ico HTTP/1.1" 404 -
192.168.0.58 - - [12/Aug/2022 22:03:36] "GET / HTTP/1.1" 404 -
192.168.0.58 - - [12/Aug/2022 22:03:36] "GET / HTTP/1.0" 404 -
192.168.0.58 - - [12/Aug/2022 22:05:34] "GET / HTTP/1.1" 404 -
Hacker Alert. Invalid Request from ('192.168.0.58', 40957)
No request in time, hacker? ('192.168.0.58', 40958)
Hacker Alert. Invalid Request from ('192.168.0.58', 40960)
Hacker Alert. Invalid Request from ('192.168.0.58', 40961)
Hacker Alert. Invalid Request from ('192.168.0.58', 40962)

**Comment by cwaddilove** [comment]
That did the trick, thanks!

I was not using HTTP before the IP. I also wasn't aware of the Remote URL, that is working fine for me.

Also one other note - I have a Slingbox M2 - using the model setting for the M1 works fine however. I was just sweating a bit initially as that model wasn't listed in your compatible models.

Thank you for your work on this project!
