### ISSUE TITLE
Server up, but cannot connect to Sling through VLC

### ISSUE THREAD

**Issue by slush99** [GerryDazoo/Slinger#232]
Hello, 

Thank you SO MUCH for all the work you put into this and for us to be able to continue using our Slingboxes!!!!!! Lots of love from Canada!

I got to the point of trying to connect to my sling through VLC, but keep getting 'your input can't be opened'.

I am entering http://192.168.1.61 into VLC.  I have also tried http://192.168.1.61:5201 with the same result.

I do have multiple slingboxes (350 and 500) and get the same result for both.

I updated the FinderID to my slingboxes FinderID in the config file (along with the IP and port).

When I run slingbox_server.exe I get:

Version : 3.08d Running on Windows-8.1-6.3.9600-SP0 pid= 3448
Using config file config.ini
Connection Manager Running on port 8080 with 10 max streams using URL slingbox.
Streamer Running:  10 config.ini SLINGBOX 8080 8080 8388608
starting up on  port 8080 8388608
Checking for slingbox at ('192.168.1.61', 5201)
('192.168.1.61', 5201) OK
8080 Using slingbox at  ('192.168.1.61', 5201)
Streamer:  8080 Waiting for first stream, flushing any IR requests that arrive while not connected to slingbox
Reading Custom Remote definition from remote.txt
 * Serving Flask app 'slingbox_server' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off

----------------------------------------------------------------------------

I've added the exception of the slingbox folder and slingbox_server.exe in my Antivirus (Kaspersky).

Any idea as to what I could be doing wrong or can point me in the right direction?  Thank you!

**Comment by JoeM2016** [comment]
Try using http://192.168.1.61:8080/slingbox in vlc

**Comment by slush99** [comment]
Thank you for the reply.

I just tried that and it gives me the same as before in VLC: your input can't be opened.

**Comment by JoeM2016** [comment]
Looks like I misunderstood your issue.  The server log looks normal to the point you published. I was chasing a VLC issue this morning where it took 5+/- times before it would connect. I did a complete VLC uninstall including the cache and preferences and reinstalled VLC. It corrected my issue for now.

**Comment by slush99** [comment]
Just tried an uninstall and reinstall of VLC, removing the cache and preferences and same result.  I have a feeling my server and setup is right, but something is up with what/how I'm entering it into VLC.  I've tried opening the following network streams:

http://192.168.1.61
http://192.168.1.61:5201
http://192.168.1.61:8080
http://192.168.1.61:8080/slingbox

**Comment by GerryDazoo** [comment]
192.168.1.161 is the IP address of your slingbox not the server.
http://ServerIPaddress:8080/slingbox

PS. Don't configure the FinderID unless you've read all the release notes and understand what and why you need to.

**Comment by slush99** [comment]
What should I be entering in VLC then?  What would my server IP address be?

**Comment by JoeM2016** [comment]
The address of the pc that the server is on.  For testing I am running the server on the same pc as VLC.

**Comment by slush99** [comment]
That worked!  Thank you so much.  
I have 3 slings, if I want to add the other 3 would I just add each one in the config?  Specifying the IP, port, etc?

**Comment by slush99** [comment]
Am I able to run 1 server with multiple slingboxes, or do I need a server for each slingbox?

**Comment by JoeM2016** [comment]
I only have 1 SB.  Check https://github.com/GerryDazoo/Slinger/discussions/85 for accessing multiple SB's

**Comment by slush99** [comment]
Thanks for the link!  And thank you all for your help!

**Comment by Mike7766** [comment]
can someone help with setup please

**Comment by GerryDazoo** [comment]
slush99: Yes, one server multiple slingboxes are supported. Please read the release notes, the unified config section.

**Comment by slush99** [comment]
Hi GerryDazoo,

I've read the release notes and have it all figured out, thank you!

It was another user "Mike7766" who was asking for help with setup.

**Comment by Mike7766** [comment]
hi GaryDazoo

can you help me with setup my you can email me mike7766@gmail.com
