### ISSUE TITLE
Works great when I run python code in Thonny Python IDE, but

### ISSUE THREAD

**Issue by skijohn877** [GerryDazoo/Slinger#299]
Works great when I run python code in Thonny Python IDE on my raspberry pi, but when I copy sling.service and try to enable with systemctl it gets an error -

root@pihole:/tmp# cat sling.log
  File "slingbox_server.py", line 363
    nonlocal sid, seq, s_ctl, dbuf, skey, stat, smode
               ^
SyntaxError: invalid syntax

**Comment by GerryDazoo** [comment]
Your using python2. THe software requires python3
