### ISSUE TITLE
Failed to execute script 'slingbox_server' due to unhandled exception

### ISSUE THREAD

**Issue by Deltapie7** [GerryDazoo/Slinger#3]
Very excited by this project. Thank you so much for the work you have done!

Windows exe ✔️ 
Folder created and files downloaded within ✔️ 
Virus exception added ✔️ 
Config file updated with password, IP of Slingbox, and port for Slingbox ✔️

Running on Windows-10-10.0.19044-SP0
Connection Manager Running 10 max streams....
Traceback (most recent call last):
  File "slingbox_server.py", line 629, in <module>
Streamer Running:
starting up on  port 8080
    <style>
ModuleNotFoundError: No module named 'flask'
07/14/2022, 21:23:21  waiting for a connection
[12240] Failed to execute script 'slingbox_server' due to unhandled exception!
Slinginfo ******* 12 30 192.168.86.214 5207
Streamer: Waiting for first stream, flushing any IR requests that arrive while not connected to slingbox

![file folder](https://user-images.githubusercontent.com/109324652/179134614-5b4993b2-d863-4462-910b-cf81ee91b1b6.png)

C:\Slingbox>(
REM if code is not on your C drive switch to the correct drive letter
 REM g:
 REM use the full pathname to where your code is located
 cd slingbox
 slingbox_server.exe
 REM or if your using python use the full path to whatever python interpreter you're using.
 REM "c:\Program Files\Python39\python.exe" slingbox_server.py
)
The directory name is invalid.
Running on Windows-10-10.0.19044-SP0
Connection Manager Running 10 max streams....
Streamer Running:
Traceback (most recent call last):
  File "slingbox_server.py", line 629, in <module>
starting up on  port 8080
07/14/2022, 21:29:06  waiting for a connection
    <style>
ModuleNotFoundError: No module named 'flask'
Slinginfo ******* 12 30 192.168.86.214 5207
[16576] Failed to execute script 'slingbox_server' due to unhandled exception!
Streamer: Waiting for first stream, flushing any IR requests that arrive while not connected to slingbox
07/14/2022, 21:29:06   connection from ('192.168.86.75', 64268)
Hacker Alert. Invalid Request from  ('192.168.86.75', 64268)
07/14/2022, 21:29:06  waiting for a connection
07/14/2022, 21:29:06   connection from ('192.168.86.75', 64267)
No Get Request in time, hacker?
07/14/2022, 21:29:06  waiting for a connection
07/14/2022, 21:29:06   connection from ('192.168.86.75', 64269)
No Get Request in time, hacker?
07/14/2022, 21:29:06  waiting for a connection
07/14/2022, 21:29:07   connection from ('192.168.86.75', 64270)
No Get Request in time, hacker?
07/14/2022, 21:29:07  waiting for a connection
07/14/2022, 21:29:07   connection from ('192.168.86.75', 64271)
Hacker Alert. Invalid Request from  ('192.168.86.75', 64271)
07/14/2022, 21:29:07  waiting for a connection
07/14/2022, 21:29:07   connection from ('192.168.86.75', 64272)
Hacker Alert. Invalid Request from  ('192.168.86.75', 64272)
07/14/2022, 21:29:07  waiting for a connection
07/14/2022, 21:29:12   connection from ('192.168.86.75', 64273)
No Get Request in time, hacker?
07/14/2022, 21:29:12  waiting for a connection
07/14/2022, 21:29:12   connection from ('192.168.86.75', 64274)
Hacker Alert. Invalid Request from  ('192.168.86.75', 64274)
07/14/2022, 21:29:12  waiting for a connection
07/14/2022, 21:29:12   connection from ('192.168.86.75', 64275)
Hacker Alert. Invalid Request from  ('192.168.86.75', 64275)
07/14/2022, 21:29:12  waiting for a connection
07/14/2022, 21:29:17   connection from ('192.168.86.75', 64276)
Hacker Alert. Invalid Request from  ('192.168.86.75', 64276)
07/14/2022, 21:29:17  waiting for a connection
07/14/2022, 21:29:17   connection from ('192.168.86.75', 64277)
Hacker Alert. Invalid Request from  ('192.168.86.75', 64277)
07/14/2022, 21:29:17  waiting for a connection
07/14/2022, 21:29:17   connection from ('192.168.86.75', 64278)
Hacker Alert. Invalid Request from  ('192.168.86.75', 64278)
07/14/2022, 21:29:17  waiting for a connection
07/14/2022, 21:29:19   connection from ('192.168.86.75', 64279)
Hacker Alert. Invalid Request from  ('192.168.86.75', 64279)
07/14/2022, 21:29:19  waiting for a connection
07/14/2022, 21:29:19   connection from ('192.168.86.75', 64280)
Hacker Alert. Invalid Request from  ('192.168.86.75', 64280)
07/14/2022, 21:29:19  waiting for a connection
07/14/2022, 21:29:19   connection from ('192.168.86.75', 64281)
Hacker Alert. Invalid Request from  ('192.168.86.75', 64281)
07/14/2022, 21:29:19  waiting for a connection
0

Config file:

[SLINGBOX]
sbtype=350
password=*******
; uncomment the next lines ipaddress and port with your local network info
; if you don't want the server to automatically find your 
; slingbox on the local network. Needed if server and slingbox are
;not on the same LAN segment. ALso removes requirement for the netifaces module  
ipaddress=192.168.86.214
port=5207

; Following are the default values
; Default resolution when server starts
Resolution=12

; Valid Values 1, 6, 10, 15, 20, 30, 60   depending on resolution
FrameRate=30

;Min 50 Max 8000
VideoBandwidth=2000

; Min 0 (auto) max 63
VideoSmoothness=63

; Send Iframe every n seconds Max 30
IframeRate=5

; Audio Bit Rate. Valid Options 16, 20, 32, 40, 48, 64, 96 Default 32
AudioBitRate=32

[SERVER]
; local port number for the server to listen on for connections
port=8080
maxstreams=10
enableremote=yes

[REMOTE]
;Key Codes : 1,4,5,9,10,11,12,13,14,15,16,17,18,19,21,22,23,24,25,26,27,28,29,31,32,33,34,35,37,38,39,40,41,42,43,44,45,46,47,53,54,55,56,57,58,59,60
; 1 = power
; 4 = chnl +
; 5 = chnl -74

; 9 = 1
; 10 = 2
; 11 = 3
;.....
; 18 = 0
; 19 = Screen format (Stretch, Wide ..... )
; 21 = chnl +
; 22 = ???
; 23 = DVR
; 24 = Play
; 25 = ???
; 26 = Pause
; 27 = Rewind
; 28 = FF
; 29 = Record
; 31 = Back 10 Seconds
; 32 = ->|
; 33 = Menu
; 34 = OnDemand
; 35 = Guide
; 37 = Exit
; 38 = "Up arrow"
; 39 = "down Arrow"
; 40 = "<-"
; 41 = "->"
; 42 = "OK"
; 43 = Page Up
; 44 = Page Down
; 45 = Favourites
; 46 = Info
; 47 = ???
; 53 = PIP on/off
; 54 = ????
; 55 = ????
; 56 = Last
; 57 = ????
; 58 = LOck PIN
; 59 = Day -
; 60 = Day +

style=.button {
      border: none;
      color: white;
      background-color: blue;
      padding: 0px 20px;
      text-align: center;
      text-decoration: none;
      display: inline-block;
      font-size: 70px;
      margin: 4px 2px;
     cursor: pointer;
    }
    .text {
      border: none;
      color: black;
      background-color: lightblue;
      text-align: center;
      text-decoration: none;
      display: inline-block;
      font-size: 70px;
      margin: 4px 2px;
      cursor: pointer;
    }
; button text, key code
buttons='1' : 9 
        :&nbsp;&nbsp;
        '2' : 10 
         :&nbsp;&nbsp;
        '3' : 11 
        :&nbsp;&nbsp;
        '4' : 12 
         :&nbsp;&nbsp;
        '5' : 13 
        :&nbsp;&nbsp;
        '6' : 14 
         :&nbsp;&nbsp;
        '7' : 15 
        :&nbsp;&nbsp;
        '8' : 16 
        :&nbsp;&nbsp;
        '9' : 17 
        :&nbsp;&nbsp;
        :&nbsp;&nbsp;
        '0' : 18 
        :<br><br>
        'OK' : 42 
         :&nbsp;&nbsp;
        'Up' : 38 
        :&nbsp;&nbsp;
        'Down' : 39 
        :&nbsp;&nbsp;
        'Left' : 40 
        :&nbsp;&nbsp;
        'Right': 41 
        :<br><br>
        :&nbsp;&nbsp;
        'Guide' : 35 
        :&nbsp;&nbsp;
        'Last' : 56         
        :&nbsp;&nbsp;
        'Exit' : 37
        :&nbsp;&nbsp;
        'DVR' : 23
        :<br><br>
        'FF' : 28
        :&nbsp;&nbsp;
        'Rew' : 27 
        :&nbsp;&nbsp;
        'Play' : 24 
        :&nbsp;&nbsp;
        'Pause' : 26 
        : <br><br>
        'Ch+' : 4
        :&nbsp;&nbsp;
        'Ch-' : 5
        :&nbsp;&nbsp;
        'Pg-' : 43 
        :&nbsp;&nbsp;
        'Pg+' : 44
        : <br><br>
        'Day-' : 59
        :&nbsp;&nbsp;
        'Day+' : 60        
        :<br><br>
        'Rec' : 29 
        :&nbsp;&nbsp;
        'OnDemand': 34
        :&nbsp;&nbsp;
        'Menu' : 33 
        :<br><br>
        'Power' : 1 
        :&nbsp;&nbsp;
        '1920x1080' : 16
        :&nbsp;&nbsp;
        '1280x720' : 12
        :<br><br>
        'Restart': Restart
        :&nbsp;&nbsp;
        'Channel': Channel

**Comment by GerryDazoo** [comment]
Check the readme. You need to use pip to install the flask module for python if you want to use the remote control functionality otherwise put in your config.ini file set enableremote=no.

 

Or

 

Use the slingbox_server.exe

 

From: Deltapie7 ***@***.***> 
Sent: Thursday, July 14, 2022 11:28 PM
To: GerryDazoo/Slinger ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [GerryDazoo/Slinger] Failed to execute script 'slingbox_server' due to unhandled exception (Issue #3)

 

Windows exe ✔️
Folder created and files downloaded within ✔️
Virus exception added ✔️
Config file updated with password, IP of Slingbox, and port for Slingbox ✔️

Running on Windows-10-10.0.19044-SP0
Connection Manager Running 10 max streams....
Traceback (most recent call last):
File "slingbox_server.py", line 629, in 
Streamer Running:
starting up on port 8080
<style>
ModuleNotFoundError: No module named 'flask'
07/14/2022, 21:23:21 waiting for a connection
[12240] Failed to execute script 'slingbox_server' due to unhandled exception!
Slinginfo ******* 12 30 192.168.86.214 5207
Streamer: Waiting for first stream, flushing any IR requests that arrive while not connected to slingbox

 <https://user-images.githubusercontent.com/109324652/179134614-5b4993b2-d863-4462-910b-cf81ee91b1b6.png>

**Comment by GerryDazoo** [comment]
Can I assume you ***********  out your password in the logs before sending?

On my box the password looks something like this..  nC4tc2XfIalAakJ

The logs look to me like you have a bad admin password. He new code will alert you to that fact.

 

*	Gerry

**Comment by Deltapie7** [comment]
You were correct, bad password. Totally my fault. ugh

Now getting the following...


Running on Windows-10-10.0.19044-SP0
Connection Manager Running 10 max streams....
Streamer Running:
starting up on  port 8085
07/15/2022, 15:43:05  waiting for a connection
Slinginfo GPgyF9IIGNUUn04 12 30 192.168.86.214 5207
Streamer: Waiting for first stream, flushing any IR requests that arrive while not connected to slingbox
07/15/2022, 15:43:08   connection from ('192.168.86.37', 61358)
07/15/2022, 15:43:08  waiting for a connection
Starting Stream for  192.168.86.37:61358
Connecting... ('192.168.86.214', 5207) Control
Exception in thread Thread-2 (streamer):
Traceback (most recent call last):
  File "threading.py", line 1009, in _bootstrap_inner
  File "threading.py", line 946, in run
  File "slingbox_server.py", line 279, in streamer
    <li class="d-flex flex-justify-center flex-items-center f5 d-none js-jump-to-suggestion p-2">
  File "slingbox_server.py", line 196, in start_slingbox_session
    <path fill-rule="evenodd" d="M1 2.75A.75.75 0 011.75 2h12.5a.75.75 0 110 1.5H1.75A.75.75 0 011 2.75zm0 5A.75.75 0 011.75 7h12.5a.75.75 0 110 1.5H1.75A.75.75 0 011 7.75zM1.75 12a.75.75 0 100 1.5h12.5a.75.75 0 100-1.5H1.75z"></path>
  File "slingbox_server.py", line 117, in dynk
    <script type="application/json" id="memex_keyboard_shortcuts_preference">"all"</script>
FileNotFoundError: [Errno 2] No such file or directory: 'keys.dat'

**Comment by GerryDazoo** [comment]
FileNotFoundError: [Errno 2] No such file or directory: 'keys.dat'

Your still  not running the latest code. That version will generate the keys.dat file on startup.

 

*	Gerry

**Comment by Deltapie7** [comment]
Sorry, not sure what i'm doing wrong. I just redownloaded the repository zip file and started over. Still stuck with the FileNotFoundError: [Errno 2] No such file or directory: 'keys.dat'

**Comment by GerryDazoo** [comment]
I did the same and I got the most recent stuff. Are you sure you unzipped it in the proper place. When you unzip  it will create a sub-folder called slinger-main.

**Comment by Deltapie7** [comment]
Just started from scratch. 

Created a folder on root of C names Slingbox ✔️
Redownloaded zip file ✔️
Unzipped file to the Slingbox folder ✔️
Virus exception added ✔️
Config file updated with password, IP of Slingbox, and port for Slingbox, no remote✔️

When running slingbox_server.exe a black box flashes and closes. 

![file folder 2](https://user-images.githubusercontent.com/109324652/179366669-e609312a-3fcd-405a-b920-6c053cd64b7e.png)

**Comment by GerryDazoo** [comment]
This in my bad. I’ll fix it soon.

 

*	Gerry

**Comment by GerryDazoo** [comment]
I’ve fixed the issue. Sorry about that..

**Comment by Deltapie7** [comment]
This is awesome! Thank you so much for putting in the time and effort!!!

**Comment by GerryDazoo** [comment]
You don’ t have the latest software. Please check out the most recent version and  delete the keys.dat before running the server for the first time.
