### ISSUE TITLE
Config.ini updates

### ISSUE THREAD

**Issue by RandomMan719** [GerryDazoo/Slinger#317]
3 minor issues

There are no video sources laid out for the pro model.  I don't know what they should be but if I find out I will add that info

Also the 350 model isn't shown, it is the same as the 350/M1/M2   0=composite 1=component

In the Config.ini it says the M1 model has S-video, it doesn't, it is the same as the M2 0=composite 1=component

Video Source  0, 1, 2, 3 depending on your hardware corresponds to one of
; Composite, Component, S-Video, HDMI or Tuner.
;  ProHD: 0=Tuner      1=Composite  2=S-Video   3=Component
;Solo/M1: 0=Composite  1=S-Video    2=Component
;    500: 0=Composite  1=Component  2=HDMI
;     M2: 0=Composite  1=Component

**Comment by GerryDazoo** [comment]
I thought the video source in the readme was already corrected (grab the latest). I don't have a pro, so I don't know for sure what they are.  Hopefully there's a few Pros out there that haven't been bricked.

**Comment by RandomMan719** [comment]
I copied that from the latest, uploaded 11 days ago.

I have a pro, only setup composite, I will figure out the source layout and let you know.

**Comment by Toei79** [comment]
question maybe can works win sb300? im been reading i guess people try with no models listed but works maybe? thanks

**Comment by RandomMan719** [comment]
> I thought the video source in the readme was already corrected (grab the latest). I don't have a pro, so I don't know for sure what they are. Hopefully there's a few Pros out there that haven't been bricked.

I was talking about the config.ini

**Comment by RandomMan719** [comment]
This should be correct, for the config.ini file.   Added Pro sources, added 350, and moved M1 with 350/M2 sources.

Video Source 0, 1, 2, 3 depending on your hardware corresponds to one of
; Composite, Component, S-Video, HDMI or Tuner.
; Pro: 0=(Analog)Tuner 1=Composite 2=S-Video 3=Component (Via HDMI to Component Cable)
; ProHD: 0=Tuner 1=Composite 2=S-Video 3=Component
; Solo: 0=Composite 1=S-Video 2=Component
; 500: 0=Composite 1=Component 2=HDMI
; 350/M1/M2: 0=Composite 1=Component

**Comment by RandomMan719** [comment]
> question maybe can works win sb300? im been reading i guess people try with no models listed but works maybe? thanks

model # SB300-XXX is the ProHD model.

**Comment by GerryDazoo** [comment]
thx

**Comment by Toei79** [comment]
> > question maybe can works win sb300? im been reading i guess people try with no models listed but works maybe? thanks
> 
> model # SB300-XXX is the ProHD model.

ok gotcha. just have one problem then right now , how i get password?  i have two units sb300 and 350. one bite the dust i reset other 350.
