### ISSUE TITLE
new router , same files - 500 won't connect again

### ISSUE THREAD

**Issue by sp222222** [GerryDazoo/Slinger#33]
500 works fine with normal paid app

I get this running python. only thing changed is my router....

S:\S2022\SLING VLC\SLING VLC\ST500_2022>ss.py config.ini
Version : 3.07 Running on Windows-7-6.1.7601-SP1 pid= 9832
Using config file config.ini
Connection Manager Running on port 5960 with 10 max streams....
Streamer Running:  10 config.ini 5960
starting up on  port 5960
Checking for slingbox at ('192.168.1.88', 5224)
Reading Custom Remote definition from S:\S2022\SLING VLC\SLING VLC\
mote_500.txt
 * Serving Flask app 'ss'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a productio
 Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5961/
 * Running on http://192.168.1.8:5961/
Press CTRL+C to quit
Error connecting to  ('192.168.1.88', 5224)
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\threading.py", line 932, in _
er
    self.run()
  File "C:\Program Files\Python38\lib\threading.py", line 870, in r
    self._target(*self._args, **self._kwargs)
  File "S:\S2022\SLING VLC\SLING VLC\ST500_2022\ss.py", line 527, i
    boxes = find_slingbox_info()
  File "S:\S2022\SLING VLC\SLING VLC\ST500_2022\ss.py", line 78, in
x_info
    import netifaces
ModuleNotFoundError: No module named 'netifaces'
08/31/2022, 02:33:01   RemoteControl connection from ('192.168.1.8'

Starting remote control stream handler for  ('192.168.1.8', 56592)
Remote Control Connected
Remote Code: 2 0x0 0x0 0x2
Button Clicked ImmutableMultiDict([('Power', '1'), ('Digits', '')])

**Comment by sp222222** [comment]
it's driving me nuts :)

**Comment by GerryDazoo** [comment]
The IP address/port for your Slingbox has changed.

“Error connecting to ('192.168.1.88', 5224)”

When that happens and it can’t find the slingbox it tries to probe for it on the network like the Sling code does. But you are missing a python module that’s needed to do the probing (“netifaces’). You should be able to install that with PIP or you can run the sling code and get the new IP/port.

 

*	Gerry

 

From: sp222222 ***@***.***> 
Sent: Wednesday, August 31, 2022 2:48 AM
To: GerryDazoo/Slinger ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [GerryDazoo/Slinger] new router , same files - 500 won't connect again (Issue #33)

 

500 works fine with normal paid app

I get this running python. only thing changed is my router....

S:\S2022\SLING VLC\SLING VLC\ST500_2022>ss.py config.ini
Version : 3.07 Running on Windows-7-6.1.7601-SP1 pid= 9832
Using config file config.ini
Connection Manager Running on port 5960 with 10 max streams....
Streamer Running: 10 config.ini 5960
starting up on port 5960
Checking for slingbox at ('192.168.1.88', 5224)
Reading Custom Remote definition from S:\S2022\SLING VLC\SLING VLC
mote_500.txt

*	Serving Flask app 'ss'
*	Debug mode: off
WARNING: This is a development server. Do not use it in a productio
Use a production WSGI server instead.
*	Running on all addresses (0.0.0.0)
*	Running on http://127.0.0.1:5961/
*	Running on http://192.168.1.8:5961/
Press CTRL+C to quit
Error connecting to ('192.168.1.88', 5224)
Exception in thread Thread-2:
Traceback (most recent call last):
File "C:\Program Files\Python38\lib\threading.py", line 932, in _
er
self.run()
File "C:\Program Files\Python38\lib\threading.py", line 870, in r
self._target(*self._args, **self._kwargs)
File "S:\S2022\SLING VLC\SLING VLC\ST500_2022\ss.py", line 527, i
boxes = find_slingbox_info()
File "S:\S2022\SLING VLC\SLING VLC\ST500_2022\ss.py", line 78, in
x_info
import netifaces
ModuleNotFoundError: No module named 'netifaces'
08/31/2022, 02:33:01 RemoteControl connection from ('192.168.1.8'

Starting remote control stream handler for ('192.168.1.8', 56592)
Remote Control Connected
Remote Code: 2 0x0 0x0 0x2
Button Clicked ImmutableMultiDict([('Power', '1'), ('Digits', '')])

**Comment by tom76017** [comment]
I force all servers on my LAN to have a fixed local IP address,  I do this in my routers DHCP.  When I upgrade my router, I have to resetup the manual DHCP addresses.   So both my Slingbox and video source (TiVo Mini) have static addresses.

**Comment by sp222222** [comment]
I gave it static IP and gave it same port IP it had before on the old
router.

pip netifaces will resolve it?  funny the remote page works but not the
sling500 itself

**Comment by GerryDazoo** [comment]
Can you send the startup output from the server. This will help in figuring out what’s happening.

**Comment by sp222222** [comment]
that’s what I posted on the github issue

**Comment by GerryDazoo** [comment]
Sorry Mike that was meant for someone  else.

**Comment by sp222222** [comment]
GerryDazoo/Slinger:

Can we schedule a time tomorrow afternoon to guide me through these
commands? Am I using putty remotely
to get into my parent’s router? And also my stumble with my 500 since
switching routers. I will try the slingsetup from Dish (owners) and see
if that works. I don’t see why my other two solos went fine once I took
them iut of dhcp pool and gave them same static IP and port they had
before, hit quickly button on the back and they both started working again.

**Comment by GerryDazoo** [comment]
Sure we can do that. What time did you have in mind? Aren’t you working days?

 

*	Gerry

**Comment by sp222222** [comment]
I should be home by 1pm ET tomorrow if you can start then. I fixed the port
issue on 500 using 3.07. I guess the default 500 port is 5213 mine was
forced to 5224 but simple changes to router fixed it. I could not get into
slingbox setuo though which makes me leary on buying another one on ebay.

We can attempt the ssh stuff tomorrow. I put the public key on parents
router and have both files ready to go. public and private key files.

Call me afternoon

Thanks

**Comment by GerryDazoo** [comment]
OK, sounds like a plan.

**Comment by sp222222** [comment]
if we need a thumb drive installed on the parents router then I’ll need to
postpone this ssh meeting. Not sure they have one but I’ll check. I have
some to give them this weekend if need be

**Comment by sp222222** [comment]
they still have the brand new one I gave them. it is now in top slot on
their router

**Comment by GerryDazoo** [comment]
FYI, your parent’s router needs the private key. Not the public.

 

From: Gerry Dubois ***@***.***> 
Sent: Wednesday, August 31, 2022 5:51 PM
To: 'GerryDazoo/Slinger' ***@***.***>; 'GerryDazoo/Slinger' ***@***.***>
Cc: 'Comment' ***@***.***>
Subject: RE: [GerryDazoo/Slinger] new router , same files - 500 won't connect again (Issue #33)

 

OK, sounds like a plan.

**Comment by sp222222** [comment]
Gerry,

If I end up replacing my PR soon, will we have to jump through the same
hoops? Or will mounting the same usb into the replacement router do the
trick?  I fear that thing won’t last long.

**Comment by GerryDazoo** [comment]
Unfortunately, there will be hoops. 

You’ll need to setup the configuration to tell PR (ASUS) to run your ssh script when it detects the USB stick and put a copy of the script in the /jffs  file system.

Good news is we already have this working so the second time around it should be mush easier. 😊

 

*	Gerry
