### ISSUE TITLE
Trying to get it working

### ISSUE THREAD

**Issue by floormanager1** [GerryDazoo/Slinger#40]
Hello, Firstly, wow, I am so grateful to you for your ingenuity in creating this.  I've been using Slingboxes for nearly 20 years and I cannot imagine life without them,  I've been trying to get this working but the VLC player just has a yellow box flashing backwards and forwards then throws an error message.  I guess I've not configured the config.ini correctly.  I'm a bit confused about the ports for the server and the slingbox.  Should they be the same?  

Version : 3.07 Running on Windows-10-10.0.19043-SP0 pid= 5804
Using config file config.ini
Connection Manager Running on port 5201 with 10 max streams....
Streamer Running:  10 config.ini 5201
starting up on  port 5201
Checking for slingbox at ('192.168.1.12', 5201)
('192.168.1.12', 5201) OK
Using slingbox at  ('192.168.1.12', 5201)
Streamer:  Slingbox 350 Waiting for first stream, flushing any IR requests that arrive while not connected to slingbox
Reading Custom Remote definition from remote.txt
 * Serving Flask app 'slingbox_server' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5202
 * Running on http://192.168.1.29:5202 (Press CTRL+C to quit)
09/06/2022, 22:21:07  Registering Slingboxes {'F295CFD982844A04220F7DD45E09671B': 5201}
Getting external IP address
Redirector, my external IP address 86.172.102.151
Registering F295CFD982844A04220F7DD45E09671B:5201

Register Successful

Any thoughts?

**Comment by abdalians** [comment]
the server port in your config.ini does not need to be the same, I suggest making it something different, but if you try to open http://192.168.1.29:5202/slingbox in VLC does that not work? 
the player should be connecting to the machine that is running this code not the slingbox.

**Comment by GerryDazoo** [comment]
You can configure any port you like. I just picked 8080 as the default for the server. This is the port VLC connects to. I think it will be confusing to use the same port number as the slingbox but you can do it if you want.

SO yes, VLC connects to the IIP address/port where the server is running not the slingbox.

**Comment by GerryDazoo** [comment]
The logs you posted look good. But I don't see any connection request coming in to stream the video.
Point VLC to http://192.168.1.29:5201/slingbox

**Comment by floormanager1** [comment]
Thank you thank you thank you!  It works!  Very happy.  You are all amazing,
