### ISSUE TITLE
black screen

### ISSUE THREAD

**Issue by abdalians** [GerryDazoo/Slinger#41]
Hello 

Thank you so much for putting time and effort into this. 
I am able to launch the python code and then vlc connects to it as well, except all I am seeing is a black screen. not the actual video. thoughts? 

`Starks Slingbox500 Starting Stream for  192.168.10.115:51795
Connecting... ('192.168.10.73', 5201) Control
cmd: 0x7e err: 0x13 176
Starks Slingbox500 Box in use! Kicking off other user.
VideoParameters: Resolution= 12 FrameRate= 30 VideoBandwidth= 2000 VideoSmoothness= 63 IframeRate= 5 AudioBitRate= 64

Connecting... ('192.168.10.73', 5201) Stream

Starks Slingbox500 Stream started at 09/06/2022, 17:44:59  744 0

........09/06/2022, 17:46:30  Starks Slingbox500 1 Clients.192.168.10.115:51770 192.168.10.115:51795

........09/06/2022, 17:48:02  Starks Slingbox500 1 Clients.192.168.10.115:51770 192.168.10.115:51795`

**Comment by GerryDazoo** [comment]
You need to select the proper VideoSource= for your box and configured input. 

On the 500  0=composite,1=component 2=HDMI

 

From: Saqib Butt ***@***.***> 
Sent: Tuesday, September 06, 2022 5:51 PM
To: GerryDazoo/Slinger ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [GerryDazoo/Slinger] black screen (Issue #41)

 

Hello

Thank you so much for putting time and effort into this.
I am able to launch the python code and then vlc connects to it as well, except all I am seeing is a black screen. not the actual video. thoughts?

Starks Slingbox500 Starting Stream for 192.168.10.115:51795 Connecting... ('192.168.10.73', 5201) Control cmd: 0x7e err: 0x13 176 Starks Slingbox500 Box in use! Kicking off other user. VideoParameters: Resolution= 12 FrameRate= 30 VideoBandwidth= 2000 VideoSmoothness= 63 IframeRate= 5 AudioBitRate= 64 Connecting... ('192.168.10.73', 5201) Stream Starks Slingbox500 Stream started at 09/06/2022, 17:44:59 744 0 ........09/06/2022, 17:46:30 Starks Slingbox500 1 Clients.192.168.10.115:51770 192.168.10.115:51795 ........09/06/2022, 17:48:02 Starks Slingbox500 1 Clients.192.168.10.115:51770 192.168.10.115:51795

**Comment by abdalians** [comment]
thank you so much for the quick response and solving my ignorance. cheers!
