### ISSUE TITLE
over the air tv antenna source

### ISSUE THREAD

**Issue by stefhenry** [GerryDazoo/Slinger#52]
Hi,

Everything is working fine with a Pro-HD but I could not use the remote to change channel?
Is there a way to change channel using source "over the air" coax antenna? This does not involve IR.

Thanks

**Comment by GerryDazoo** [comment]
If you can change channels with the Slingbox remote you should be able to get my code to do the same. Please read the release note. Make sure it's working with the Sling software first.

No there is no way to change the source using the antenna.
