### ISSUE TITLE
Server not running on Windows 10 Home

### ISSUE THREAD

**Issue by floormanager1** [GerryDazoo/Slinger#53]
Hello, after the success earlier, I thought I'd install the server on an old laptop running a fresh install of Windows 10 Home.  When I run the RunSling.bat file, the screen rolls over with the error 'This version of C:\...\slingbox_server.exe is not compatible with the version of Windows you're running'.

If I try to run the sling-server.exe file, I get a Windows' error stating 'This app can't run on your PC'. 

The server works perfectly on other Windows 10 laptops.  What am I missing?
Thank you
Paul

**Comment by GerryDazoo** [comment]
Maybe a 32 bit vs 64 bit issue. How old is that laptop? You may need to poke into the BIOS to enable 64 bit.

 

From: floormanager1 ***@***.***> 
Sent: Sunday, September 11, 2022 5:18 AM
To: GerryDazoo/Slinger ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [GerryDazoo/Slinger] Server not running on Windows 10 Home (Issue #53)

 

Hello, after the success earlier, I thought I'd install the server on an old laptop running a fresh install of Windows 10 Home. When I run the RunSling.bat file, the screen rolls over with the error 'This version of C:...\slingbox_server.exe is not compatible with the version of Windows you're running'.

If I try to run the sling-server.exe file, I get a Windows' error stating 'This app can't run on your PC'.

The server works perfectly on other Windows 10 laptops. What am I missing?
Thank you
Paul

**Comment by floormanager1** [comment]
Thanks, I'll have a look :-)

**Comment by floormanager1** [comment]
Right again!  Reinstalled with X64 and we're off and running.  Thank you for all your excellent work.
