### ISSUE TITLE
SlingerPlayer 4.0 not ready for prime time

### ISSUE THREAD

**Issue by robosmith** [GerryDazoo/Slinger#536]
Tried out the new 4.0 release sw with SlingerPlayer and it kinda worked but crashed.
On shutdown, it displayed a memory leak dialog;
![SlingerPlayer mem leak](https://user-images.githubusercontent.com/4614624/219819302-fcf9b418-7e86-4ccb-ae32-2587ff054abf.jpg)

**Comment by GerryDazoo** [comment]
Could you be a little more specific about what "kinda worked" means.
Also some more details on the "crash".

**Comment by almoney** [comment]
I have been running Slingerplayer 4.0 on a Surface Go (small tablet) for the last 3 days and see no issues.  The only thing I would want to improve is scaling the remote to fit in the space available.

**Comment by GerryDazoo** [comment]
Jeff, RE: Remote. The remote window is a "standard" browser. You can resize the text with the ctrl +/-.  But as you know depending on the remote type, test or HTML it gets redrawn when the key click gets posted. 
You can always just make your remote window bigger. Unfortunately I haven't been able to figure out how to make the remote fit the window. If there's any Javascript/HTML experts out there an example would be helpful. But it would seen that trying to make that work is counter-intuitive to how web pages are supposed to be rendered.
But what I've done is I just changed the remote definition file to use a smaller font which is fine for running on the PC. The original default size was one I picked out of the air was to make the buttons big enough for my fat fingers to press when using my phone for a remote.

**Comment by sp222222** [comment]
only time I get a crash is when my remote (PR) slingbox is having connection issues. 

works fine internal network.

**Comment by GerryDazoo** [comment]
Try this. I gets rid of the MemoryLeak dialog when you X out the app while it is trying to connect.
[SlingerPlayer.zip](https://github.com/GerryDazoo/Slinger/files/10774999/SlingerPlayer.zip)

**Comment by robosmith** [comment]
> Might there be a bug or two, quite possibly. I'll need to fire my crack team of system testers. But comments like this are particularly unhelpful. Could you be a little more specific about what "kinda worked" means. Also some more details on the "crash". Can you reproduce it? If so please response with some useful information. I've not used anything except SlingerPlayer for streaming since Christmas and others have had no issues. Here's some comment's I've received, "Used V4 to watch TV last night and it worked really well." "player runs solid." "this is dang near like watching normal TV with the player response time"

Kinda worked means it was able to display video initially, but when I sent commands to the Tivo they took a long time to show up on the screen; much longer than a freshly run VLC. I will try your new release and see if I can nail down exactly what conditions cause a crash.

**Comment by donbru52** [comment]
I'm seeing the exact same error.  Server is a Raspberry Pi running on Debian Bullseye 64bit lite.  It happens when starting to connect on SlingerPlayer and it never finishes the connection.  The only way I've found to work around it is to shutdown SlingerPlayer and restart.  That error box appears on the screen right after shutting down.  The Slingbox ProHD is connected to a TiVo Mini.

**Comment by GerryDazoo** [comment]
Use the exe I posted earlier.

**Comment by GerryDazoo** [comment]
Robo,
An out of the box VLC has about 4 seconds of default buffering, SlingerPlayer out of the box is configured with minimal buffering. I'm seeing response times of about a second. So there's something else going on. 
- Gerry
-

**Comment by donbru52** [comment]
I am using the exe on a Windows 10 laptop although it is the one dated 1/15/2023.  The video resolution on the versions that were posted this month don't fill the screen vertically.  The video resolution is set to 16 although I've also tried a setting of 12 with the same result.  The error screen seems to only happen when connecting to the Sling server on the Pi.  I've installed the server on three Windows PCs and SlingerPlayer doesn't exhibit the same issue.

**Comment by GerryDazoo** [comment]
Please post a screenshot. Fullscreen should be fullscreen no matter what.

**Comment by donbru52** [comment]
![Screenshot 2023-02-19 095227](https://user-images.githubusercontent.com/125776790/219955888-b53c2bb2-2b75-418f-a20f-29404dd4f61c.png)


![Screenshot 2023-02-19 095330](https://user-images.githubusercontent.com/125776790/219955890-89a00929-0edd-47af-9df3-f0221d0c2f27.png)

**Comment by GerryDazoo** [comment]
What are you feeding the Pro? looks like you've got a 1920x540 video stream. I was just watching that channel. Her'e what I see with the same parameters.
![image](https://user-images.githubusercontent.com/102599361/219958034-48be496f-18fd-4ce8-bb83-8f2b2da90136.png)

ProHD Selecting Video Source 3
ProHD Keycodes= [1, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 21, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 35, 36, 38, 39, 40, 41, 42, 43, 44, 46, 53, 56, 57, 59, 60, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80]
VideoParameters: Resolution= 16 FrameRate= 30 VideoBandwidth= 2048 VideoSmoothness= 63 IframeRate= 5 AudioBitRate= 96

What device are you viewing on?

**Comment by donbru52** [comment]
And here is what I get with the one dated 1/15/2023

![Screenshot 2023-02-19 105626](https://user-images.githubusercontent.com/125776790/219959420-fd895642-af16-4a7d-9e47-6ac6569f5767.png)

The Pro-HD is connected to a TiVo meaning.  I'm not sure what is included in the updates but this version works flawlessly.

**Comment by donbru52** [comment]
I'm viewing this on a HP Envy Windows 10 laptop.

**Comment by donbru52** [comment]
Found the problem.  Just loaded SlingerPlayer dated 02/17/2023 and it works again.  The file I was having the issue with was from 02/13/2023.

**Comment by GerryDazoo** [comment]
Slinger Player stuff now has it's own repository
https://github.com/GerryDazoo/SlingerPlayer
