### ISSUE TITLE
How do I use remote?

### ISSUE THREAD

**Issue by JLBla** [GerryDazoo/Slinger#55]
Thank you for allowing us to use our Slingbox.  I am connecting my Windows 11 PC with my M1 Slingbox using VLC.  I was able to stream live TV with my DirecTV HR24 using VLC with 192.168.2.222/slingbox; however, I do not know how to get the remote to work.  Every time I try to open 192.168.2.222/remote with VLC, it says that it is unable to open and look at the log.  

The slingbox_server.exe shows 
Starting remote control stream handler for  ('192.168.2.222', 57346) to port 8081
Remote Control Connected
127.0.0.1 - - [11/Sep/2022 16:04:22] "GET /remote HTTP/1.0" 404 -
Exiting Remote Control Stream Handler for ('192.168.2.222', 57346)

I am not sure how I am supposed to be using the remote function.  Please help.  Thank you.

**Comment by GerryDazoo** [comment]
192.168.2.222/remote

It’s Remote not remote and you don’ tput this into VLC but use a standard web browser.

 

From: JLBla ***@***.***> 
Sent: Sunday, September 11, 2022 5:09 PM
To: GerryDazoo/Slinger ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [GerryDazoo/Slinger] How do I use remote? (Issue #55)

 

Thank you for allowing us to use our Slingbox. I am connecting my Windows 11 PC with my M1 Slingbox using VLC. I was able to stream live TV with my DirecTV HR24 using VLC with 192.168.2.222/slingbox; however, I do not know how to get the remote to work. Every time I try to open 192.168.2.222/remote with VLC, it says that it is unable to open and look at the log.

The slingbox_server.exe shows
Starting remote control stream handler for ('192.168.2.222', 57346) to port 8081
Remote Control Connected
127.0.0.1 - - [11/Sep/2022 16:04:22] "GET /remote HTTP/1.0" 404 -
Exiting Remote Control Stream Handler for ('192.168.2.222', 57346)

I am not sure how I am supposed to be using the remote function. Please help. Thank you.

**Comment by JLBla** [comment]
Thank you.  I was able to get it to work by using a browser for the remote.  I was wondering if it was hard to create some buttons for the remote.  The DirecTV remote has buttons for red, yellow, green, and blue.

**Comment by GerryDazoo** [comment]
Have a look at the Tivo remotes in the CustomRemotes folder for examples.
