### ISSUE TITLE
Custom remote ProHD_Tuner.txt channel number button doesn't work

### ISSUE THREAD

**Issue by mike-uk** [GerryDazoo/Slinger#570]
For ProHD_Tuner.txt Ch+ Ch- and last works but when enter channel number it try to send out ir key instead of changing the internal tuner. For example when I enter 1 it out put ir key 9.

03/26/2023, 10:17:21.8  MySlingbox Sending IR keycode 9 0 for 192.168.1.162
sending key 9 0

**Comment by GerryDazoo** [comment]
you need to put a decimal point in the channel number. In US something like 4.0 or 9.1 In the UK just the channel#  127.

Keycode nine is the digit 1 on the remote.
