### ISSUE TITLE
Tivo Remote Functions

### ISSUE THREAD

**Issue by rblancarte** [GerryDazoo/Slinger#60]
Just found this, installed it on a raspberry pi - works like a charm ...

... almost.

So my Slingbox is hooked up to a Tivo Mini. The remote has a few more functions that aren't on available via the standard remote. Do you know what these function are? Is there an easy way to find out? I'm tinkering w/ the remote.txt file - that seems pretty easy, but things like the LIVE TV button don't work (function 32 - LIVE isn't it).

**Comment by GerryDazoo** [comment]
Check out the Tivo remote files in the CustomRemotes folder.

**Comment by rblancarte** [comment]
Thanks! I ended up finding the code via brute force. But those files are far better than anything I could have done. Thanks!
