### ISSUE TITLE
Slingbox Pro factory reset , error when connecting

### ISSUE THREAD

**Issue by flipper2222222** [GerryDazoo/Slinger#624]
hi all, 
using slinger 4.0
maybe someone knows what this output means or how to fix? thanks in advance.

Slinginfo  "Solo/Pro/ProHD" 12 30 192.168.0.237 6001 3000 10 qwe
red2 Starting Stream for  192.168.0.222:28427
red2 Opening Control stream 0x2000 0 0
Connecting... ('192.168.0.237', 6001) Control
cmd: 0x67 err: 0x2b 8
Traceback (most recent call last):
  File "slingbox_server.py", line 836, in streamer
    print( ts(), name, '%d Clients.' % len(streams), end='')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "slingbox_server.py", line 367, in start_slingbox_session
    if smode == 0x8000 :
             ^^^^^
NameError: name 'start' is not defined
red2 Badness starting slingbox session  name 'start' is not defined None
Streamer:  red2 Waiting for first stream, flushing any IR requests that arrive while not connected to slingbox

**Comment by GerryDazoo** [comment]
please us the latest version 4.01

**Comment by flipper2222222** [comment]
thanks now using 4.01
some other notes, I got this on ebay but confirmed it wasn't turned on post sling server shutdown
I have blocked internet access to the slingbox's IP address, got another error see below, is there any other explanation other than the bricked message indication?

Slinginfo  "Solo/Pro/ProHD" 12 30 192.168.0.237 6001 3000 10 qwe
red2 Starting Stream for  192.168.0.222:4907
red2 Opening Control stream 0x2000 0 0
Connecting... ('192.168.0.237', 6001) Control
cmd: 0x67 err: 0x2b 8
red2 Error Starting Session. Slingbox might be Bricked
red2 ERROR: Slingbox session startup failed.
red2 Logging Out
Streamer:  red2 Waiting for first stream, flushing any IR requests that arrive while not connected to slingbox

**Comment by flipper2222222** [comment]
thanks a lot Gerry, I thought I had blocked internet access by IP with mac reservation and firewall block, but for some reason it has picked up a different IP, V4.01 advised that it is bricked, I will reset it again and set it up as per the Slingbox.PRO-HD.Unbricking.Guide which appeard to work when I attempted it last week.

**Comment by flipper2222222** [comment]
reset again and all good now, thanks again
