### ISSUE TITLE
v4.0+: Slingbox status no longer shows at bottom of "Remote" web page.

### ISSUE THREAD

**Issue by knoppix1337** [GerryDazoo/Slinger#626]
In version 3.08f; the "Remote" web page rendering shows following status info at the bottom of the page: 

IP address of the connected slingbox, 
The number of connections or waiting status,
and the packets sent. 

I liked having this info, mostly the number of connected boxes, so I can tell if I left a session connected somewhere (I have a low upstream bandwidth connection, and can only support one WAN client).

The "packets sent" update would also help to show a button press was submitted.

I know you said you improved response time on the remote buttons in v4.0+. Is this one of the ways? It would be nice if we could have a debug mode or flag or whatever for the people who still want or rely on this info.

**Comment by GerryDazoo** [comment]
Make sure the page has the text "Status:%s"
