### ISSUE TITLE
only getting onto remote slingbox from client running your server.exe in another state

### ISSUE THREAD

**Issue by sp222222** [GerryDazoo/Slinger#63]
It has been working for days (eight) and then it worked fine Friday night thru Sunday night.
(watched both NFL and then Men's USOpen tennis immediately after yesterday).
We added the script (friday evening) to boot up with PR and it worked all weekend. 

So today I come home from work and the one slingbox that is not on my home network won't connect from my laptop downstairs.
I rebooted both my router and the remote (out of state) router. Now, I can only connect to that out of state slingbox using the desktop I have upstairs that is the server for all the slingboxes. I've changed nothing in 3 days. (Wasn't even home to change things anyways).  I'm seeing no errors on slingserver python script when it starts on my desktop server. This is very confusing why it works on only one client.

Any ideas Gerry?

**Comment by sp222222** [comment]
it works now again. not sure what changed.

**Comment by GerryDazoo** [comment]
Weird, firewall/routing issue? Do you have the program output from when it failed? I'd like to take a look.

**Comment by GerryDazoo** [comment]
Did you have your VPN turned on?

**Comment by sp222222** [comment]
never showed failed, can I see these ssh connections from PR logs?
I saw a setting under ssh I guess password was off or something idk. it
baffles me that it would work on only one client in my house. no , my vpn
was off on all clients at the time

**Comment by GerryDazoo** [comment]
If there were no errors it means that the sever could talk out to all the slingboxes. So it would seem like something was blocking the incoming connections to the server. If only your parents was accessible then I would guess the firewall was allowing that port and blocking the other server ports. Double check you firewall that you have rules to allow connections for all your server ports.

You can verify the SSH connection is up by logging into either router and doing a 
"netstat -an | grep ssh_port_number  (whatever that was 39???)
