### ISSUE TITLE
Is it possible to change the url slingbox?

### ISSUE THREAD

**Issue by f520k510** [GerryDazoo/Slinger#68]
I wonder if it is possible to allow user to change the url from slingbox to something else?
How about if we take the name value in the config.ini and add it the url.
Foe example, if name=ts/0, then the url becomes http://ip:8080/ts/0

This is for security reason, if someone know my ip, he maybe able to randomly guess the port.
Just a suggestion.  We can always change the maxstreams=1 anyway.

**Comment by GerryDazoo** [comment]
We''ll there's 65535 possible ports so it might take some time to randomly guess. Does sombody really want to watch your slingbox that badly? 
Anyho,, that feature is in the next release, coming soon. Would you be will to take it out for a test drive?

**Comment by f520k510** [comment]
yes, please.

**Comment by f520k510** [comment]
How can I get the file?  I assume it is the slingbox_server.py.

**Comment by GerryDazoo** [comment]
Let me put it on my web server and I’ll post the link. Here’s the work in progress release notes.

**Comment by GerryDazoo** [comment]
http://home.dazoo.net:65480/Slinger/slingbox_server_3.08_beta.py

**Comment by GerryDazoo** [comment]
E-mail directly for support gerry@dazzo.net.
Let me know when you get this, so I can delete this message  and try to keep my email private.

**Comment by f520k510** [comment]
Hi, I was asleep when you post the link.  It was night time.
I just woke up.  PLease allow me access to the file again.
Thanks.

**Comment by f520k510** [comment]
I email you to the above email address.  It returned with domain not found.

**Comment by GerryDazoo** [comment]
typo, sorry gerry@dazoo.net
You should be able to download it anytime there are no restrictions.

**Comment by f520k510** [comment]
Hi, I am not able to download it.
Can you please check your email and reply to me?

**Comment by GerryDazoo** [comment]
taking offline
