### ISSUE TITLE
Rename config.ini to config.ini.sample

### ISSUE THREAD

**Issue by mpagano** [GerryDazoo/Slinger#75]
First of all, thank-you 100 times for your work.

Any thoughts on renaming config.ini to config.ini.sample (or something similar) so we can do simple git pulls without conflicts ?

**Comment by GerryDazoo** [comment]
Or you can change your config.ini file name to my_config.ini and run
slingbox_server  my_config.ini

**Comment by mpagano** [comment]
Prefect ! Thanks, that will work.
