### ISSUE TITLE
Fail to fetch Keys.dat

### ISSUE THREAD

**Issue by wawatsou** [GerryDazoo/Slinger#9]
Hi Gerry,

I have run the server on a proxmox container, but failed to fetch the keys.dat. Following are the log file. Only IP and port in config.ini was changed and the firewall of the server has been disable. It will be greatly appreciated to know what's wrong I have made.
Thank you very much in advance.

Version : 1.01 Running on Linux-5.15.39-1-pve-x86_64-with-glibc2.31
Connection Manager Running 10 max streams....
Streamer Running: 
starting up on  port 8080
Checking  ('10.88.88.37', 5222)
Using slingbox at  ('10.88.88.37', 5222)
Streamer: Waiting for first stream, flushing any IR requests that arrive while not connected to slingbox
 * Serving Flask app 'slingbox_server' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:9998
 * Running on http://10.88.88.250:9998 (Press CTRL+C to quit)
07/21/2022, 03:19:09   connection from ('10.88.88.2', 59422)

Slinginfo  500 huc**********O9H0 12 30 10.88.88.37 5222 3072
Starting Stream for  10.88.88.2:59422
Connecting... ('10.88.88.37', 5222) Control
CHALLANGE 4f42722b29b802d74616a64c78e0a6d4
Badness starting slingbox session  unpack requires a buffer of 16 bytes

In keys.dat

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access this resource.</p>
</body></html>

**Comment by wawatsou** [comment]
I found that I can't fetch the keys.dat because of my IP area. After using IP in US, I can successfully get the file and it works. Thanks  Gerry.

**Comment by GerryDazoo** [comment]
What location are you in? Can you share your external IP address. I had forgotten the server with the keys only allows connections from North America due to the non-stop hacking attempts from Eastern Europe and China.

 

*	Gerry

**Comment by wawatsou** [comment]
I am in Taiwan and using dynamic IP address. However, I can get the keys.dat file by using a VPN server in US.  

Thanks a lot for your great work.

**Comment by wawatsou** [comment]
One more question.

I can successfully connect and watch the video at first time, but will instantly disconnet afterthen with error number 32. Following is the log file. May I know how to fix it. Thank you.



Version : 1.01 Running on Linux-5.15.39-1-pve-x86_64-with-glibc2.31
Connection Manager Running 10 max streams....
Streamer Running: 
starting up on  port 8888
Checking  ('10.88.88.37', 5222)
Using slingbox at  ('10.88.88.37', 5222)
Streamer: Waiting for first stream, flushing any IR requests that arrive while not connected to slingbox
 * Serving Flask app 'slingbox_server' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:9998
 * Running on http://10.88.88.250:9998 (Press CTRL+C to quit)
07/22/2022, 04:04:15   connection from ('10.88.88.2', 38432)

Slinginfo  500 hucZXW*********H0 16 30 10.88.88.37 5222 3072
Starting Stream for  10.88.88.2:38432
Connecting... ('10.88.88.37', 5222) Control
CHALLANGE 4f42722b29b802d74616a64c78e0a6d4
VideoParameters: Resolution= 16 FrameRate= 30 VideoBandwidth= 2000 VideoSmoothness= 0 IframeRate= 5 AudioBitRate= 64
Connecting... ('10.88.88.37', 5222) Stream
h246_header_pos 745 745
Stream started at 07/22/2022, 04:04:18  745
07/22/2022, 04:04:20  Stream Terminated for  10.88.88.2:38432 [Errno 32] Broken pipe
Streamer: Waiting for first stream, flushing any IR requests that arrive while not connected to slingbox

**Comment by GerryDazoo** [comment]
That error is caused by your client closing the TCP connection to the server for whatever reason. What software are you using?

There may be some logs but it sounds like it’s not syncing up with the video stream. BTW, 16 is not a valid video resolution it goes from 0-15. This could be your problem. Try 12 (1280x720).

 

*	Gerry

**Comment by wawatsou** [comment]
I was using VLC on an Android phone with VPN connect to local network. Changing resolution to 12 also has same situation.

Thank you much for your patience to verify the issues. 

**Here is the logs of server.**
Version : 1.01 Running on Linux-5.15.39-1-pve-x86_64-with-glibc2.31
Connection Manager Running 10 max streams....
Streamer Running: 
Checking  ('10.88.88.37', 5222)
starting up on  port 8888
Using slingbox at  ('10.88.88.37', 5222)
Streamer: Waiting for first stream, flushing any IR requests that arrive while not connected to slingbox
 * Serving Flask app 'slingbox_server' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:9998
 * Running on http://10.88.88.250:9998 (Press CTRL+C to quit)
07/22/2022, 10:27:53   connection from ('10.88.88.3', 50624)

Slinginfo  500 hucZXWR40w4O9H0 12 30 10.88.88.37 5222 3072
Starting Stream for  10.88.88.3:50624
Connecting... ('10.88.88.37', 5222) Control
CHALLANGE 4f42722b29b802d74616a64c78e0a6d4
VideoParameters: Resolution= 12 FrameRate= 30 VideoBandwidth= 2000 VideoSmoothness= 63 IframeRate= 5 AudioBitRate= 64
Connecting... ('10.88.88.37', 5222) Stream
h246_header_pos 749 2197
Stream started at 07/22/2022, 10:27:57  749
07/22/2022, 10:28:01  Stream Terminated for  10.88.88.3:50624 [Errno 32] Broken pipe
Streamer: Waiting for first stream, flushing any IR requests that arrive while not connected to slingbox

**Comment by GerryDazoo** [comment]
Can you try a different client ( mplayer ). Do you already have a port mapping on your router to allow access to your slingbox? I might be able to connect remotely to debug.

 

*	Gerry

**Comment by wawatsou** [comment]
Are you meant a port mapping to Slingbox control port 5222 or the server port access by VLC?

I have tried MXplayer and is the same.

Thanks in advance.

 


> Can you try a different client ( mplayer ). Do you already have a port mapping on your router to allow access to your slingbox? I might be able to connect remotely to debug. * Gerry

**Comment by GerryDazoo** [comment]
The slingbox control port 5222

**Comment by wawatsou** [comment]
Weird. I can successfully use PlayerXtreme to paly without problem, but not VLC and MXplayer.

Please reach my Slingbox at 1.160.30.217 port 33355. Thanks again.

**Comment by GerryDazoo** [comment]
I did mis-speak. 16 is a valid resolution  1920x1080 IFF you have a 500/M1 slingbox. Is that what you’re feeding?

What version of VLC are you using. I have no problems with VLC on my android  phone.

**Comment by wawatsou** [comment]
I am using VLC 012337e36 version on an Android phone.
Yesterday when I used the file of slingbox_server.py in the new commits (not the newest one posted 4 hours ago), everything worked great without problem. But when I used the newest one posted 4 hours ago, Immediate disconnect happened again.

Thanks for your patients to deug. 

> I did mis-speak. 16 is a valid resolution 1920x1080 IFF you have a 500/M1 slingbox. Is that what you’re feeding? What version of VLC are you using.

**Comment by GerryDazoo** [comment]
I have no explanation for that. The latest commit had a two line change to fix an issue with sending remote control commands. It should have had no effect on the video stream. Are you using the Python code or the Windows exe? 

I’m not sure what to tell you , no one else is having an issue like this. I’ll need your slingbox password to be able to connect remotely for debugging.

 

*	Gerry
