### ISSUE TITLE
Pro HD remote for Coaxial Input

### ISSUE THREAD

**Issue by lomanneh61** [GerryDazoo/Slinger#91]
I cannot get the remote to work with Slingbox Pro HD Tuner input. Can anyone Help please.

**Comment by GerryDazoo** [comment]
Make sure your using the proper url  http://serverip:serverport/Remote   !!Capitial R
Select the proper VideoSource per the info in the default config.ini

**Comment by lomanneh61** [comment]
I am sorry if I am not clear on my issue above. I got the webpage to load but it is not changing channels. I am using over the air antenna connected to the Pro HD. The Sling Player for web antenna remote works just fine for changing channel. I try to change my code and Video Source to 0 and other combinations but nothing works. I try to uncomment remote.txt but that did not work either. 

> Make sure it's working with the Sling software first. Make sure your using the proper url http://serverip:serverport/Remote !!Capitial R Select the proper VideoSource per the info in the defau
